/* Channel.c generated by valac 0.12.0, the Vala compiler
 * generated from Channel.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define DAEMON_IRC_TYPE_CHANNEL (daemon_irc_channel_get_type ())
#define DAEMON_IRC_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_IRC_TYPE_CHANNEL, DaemonIRCChannel))
#define DAEMON_IRC_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_IRC_TYPE_CHANNEL, DaemonIRCChannelClass))
#define DAEMON_IRC_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_IRC_TYPE_CHANNEL))
#define DAEMON_IRC_IS_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_IRC_TYPE_CHANNEL))
#define DAEMON_IRC_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_IRC_TYPE_CHANNEL, DaemonIRCChannelClass))

typedef struct _DaemonIRCChannel DaemonIRCChannel;
typedef struct _DaemonIRCChannelClass DaemonIRCChannelClass;
typedef struct _DaemonIRCChannelPrivate DaemonIRCChannelPrivate;
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _DaemonIRCChannel {
	GObject parent_instance;
	DaemonIRCChannelPrivate * priv;
};

struct _DaemonIRCChannelClass {
	GObjectClass parent_class;
};

struct _DaemonIRCChannelPrivate {
	GList* _activeUsers;
	gchar* _Name;
};


static gpointer daemon_irc_channel_parent_class = NULL;

GType daemon_irc_channel_get_type (void) G_GNUC_CONST;
#define DAEMON_IRC_CHANNEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DAEMON_IRC_TYPE_CHANNEL, DaemonIRCChannelPrivate))
enum  {
	DAEMON_IRC_CHANNEL_DUMMY_PROPERTY,
	DAEMON_IRC_CHANNEL_ACTIVE_USERS,
	DAEMON_IRC_CHANNEL_NAME
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
DaemonIRCChannel* daemon_irc_channel_new (const gchar* name);
DaemonIRCChannel* daemon_irc_channel_construct (GType object_type, const gchar* name);
static void daemon_irc_channel_set_Name (DaemonIRCChannel* self, const gchar* value);
void daemon_irc_channel_UserJoined (DaemonIRCChannel* self, const gchar* name);
GList* daemon_irc_channel_get_ActiveUsers (DaemonIRCChannel* self);
void daemon_irc_channel_UserLeft (DaemonIRCChannel* self, const gchar* name);
void daemon_irc_channel_UserChangedName (DaemonIRCChannel* self, const gchar* name, const gchar* newName);
const gchar* daemon_irc_channel_get_Name (DaemonIRCChannel* self);
static void daemon_irc_channel_finalize (GObject* obj);
static void _vala_daemon_irc_channel_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_daemon_irc_channel_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


DaemonIRCChannel* daemon_irc_channel_construct (GType object_type, const gchar* name) {
	DaemonIRCChannel * self = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (DaemonIRCChannel*) g_object_new (object_type, NULL);
	daemon_irc_channel_set_Name (self, name);
	return self;
}


DaemonIRCChannel* daemon_irc_channel_new (const gchar* name) {
	return daemon_irc_channel_construct (DAEMON_IRC_TYPE_CHANNEL, name);
}


void daemon_irc_channel_UserJoined (DaemonIRCChannel* self, const gchar* name) {
	GList* _tmp0_ = NULL;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = daemon_irc_channel_get_ActiveUsers (self);
	_tmp1_ = g_strdup (name);
	_tmp0_ = g_list_append (_tmp0_, _tmp1_);
}


void daemon_irc_channel_UserLeft (DaemonIRCChannel* self, const gchar* name) {
	GList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = daemon_irc_channel_get_ActiveUsers (self);
	_tmp0_ = g_list_remove (_tmp0_, name);
}


void daemon_irc_channel_UserChangedName (DaemonIRCChannel* self, const gchar* name, const gchar* newName) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (newName != NULL);
	daemon_irc_channel_UserLeft (self, name);
	daemon_irc_channel_UserJoined (self, newName);
}


GList* daemon_irc_channel_get_ActiveUsers (DaemonIRCChannel* self) {
	GList* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_activeUsers;
	return result;
}


const gchar* daemon_irc_channel_get_Name (DaemonIRCChannel* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Name;
	return result;
}


static void daemon_irc_channel_set_Name (DaemonIRCChannel* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Name);
	self->priv->_Name = _tmp0_;
	g_object_notify ((GObject *) self, "Name");
}


static void daemon_irc_channel_class_init (DaemonIRCChannelClass * klass) {
	daemon_irc_channel_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DaemonIRCChannelPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_daemon_irc_channel_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_daemon_irc_channel_set_property;
	G_OBJECT_CLASS (klass)->finalize = daemon_irc_channel_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), DAEMON_IRC_CHANNEL_ACTIVE_USERS, g_param_spec_pointer ("ActiveUsers", "ActiveUsers", "ActiveUsers", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DAEMON_IRC_CHANNEL_NAME, g_param_spec_string ("Name", "Name", "Name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void daemon_irc_channel_instance_init (DaemonIRCChannel * self) {
	self->priv = DAEMON_IRC_CHANNEL_GET_PRIVATE (self);
	self->priv->_activeUsers = NULL;
}


static void daemon_irc_channel_finalize (GObject* obj) {
	DaemonIRCChannel * self;
	self = DAEMON_IRC_CHANNEL (obj);
	__g_list_free__g_free0_0 (self->priv->_activeUsers);
	_g_free0 (self->priv->_Name);
	G_OBJECT_CLASS (daemon_irc_channel_parent_class)->finalize (obj);
}


GType daemon_irc_channel_get_type (void) {
	static volatile gsize daemon_irc_channel_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_irc_channel_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DaemonIRCChannelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) daemon_irc_channel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DaemonIRCChannel), 0, (GInstanceInitFunc) daemon_irc_channel_instance_init, NULL };
		GType daemon_irc_channel_type_id;
		daemon_irc_channel_type_id = g_type_register_static (G_TYPE_OBJECT, "DaemonIRCChannel", &g_define_type_info, 0);
		g_once_init_leave (&daemon_irc_channel_type_id__volatile, daemon_irc_channel_type_id);
	}
	return daemon_irc_channel_type_id__volatile;
}


static void _vala_daemon_irc_channel_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DaemonIRCChannel * self;
	self = DAEMON_IRC_CHANNEL (object);
	switch (property_id) {
		case DAEMON_IRC_CHANNEL_ACTIVE_USERS:
		g_value_set_pointer (value, daemon_irc_channel_get_ActiveUsers (self));
		break;
		case DAEMON_IRC_CHANNEL_NAME:
		g_value_set_string (value, daemon_irc_channel_get_Name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_daemon_irc_channel_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DaemonIRCChannel * self;
	self = DAEMON_IRC_CHANNEL (object);
	switch (property_id) {
		case DAEMON_IRC_CHANNEL_NAME:
		daemon_irc_channel_set_Name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



