/* IRCConnection.c generated by valac 0.12.0, the Vala compiler
 * generated from IRCConnection.vala, do not modify */

/*SemesterLeistung - An IRC Daemon
* Copyright (C) 2011  Simon Baumer
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>


#define DAEMON_IRC_TYPE_IRC_CONNECTION (daemon_irc_irc_connection_get_type ())
#define DAEMON_IRC_IRC_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_IRC_TYPE_IRC_CONNECTION, DaemonIRCIRCConnection))
#define DAEMON_IRC_IRC_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_IRC_TYPE_IRC_CONNECTION, DaemonIRCIRCConnectionClass))
#define DAEMON_IRC_IS_IRC_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_IRC_TYPE_IRC_CONNECTION))
#define DAEMON_IRC_IS_IRC_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_IRC_TYPE_IRC_CONNECTION))
#define DAEMON_IRC_IRC_CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_IRC_TYPE_IRC_CONNECTION, DaemonIRCIRCConnectionClass))

typedef struct _DaemonIRCIRCConnection DaemonIRCIRCConnection;
typedef struct _DaemonIRCIRCConnectionClass DaemonIRCIRCConnectionClass;
typedef struct _DaemonIRCIRCConnectionPrivate DaemonIRCIRCConnectionPrivate;

#define DAEMON_CONFIGURATION_TYPE_SERVER_CONFIGURATION (daemon_configuration_server_configuration_get_type ())
#define DAEMON_CONFIGURATION_SERVER_CONFIGURATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_CONFIGURATION_TYPE_SERVER_CONFIGURATION, DaemonConfigurationServerConfiguration))
#define DAEMON_CONFIGURATION_SERVER_CONFIGURATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_CONFIGURATION_TYPE_SERVER_CONFIGURATION, DaemonConfigurationServerConfigurationClass))
#define DAEMON_CONFIGURATION_IS_SERVER_CONFIGURATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_CONFIGURATION_TYPE_SERVER_CONFIGURATION))
#define DAEMON_CONFIGURATION_IS_SERVER_CONFIGURATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_CONFIGURATION_TYPE_SERVER_CONFIGURATION))
#define DAEMON_CONFIGURATION_SERVER_CONFIGURATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_CONFIGURATION_TYPE_SERVER_CONFIGURATION, DaemonConfigurationServerConfigurationClass))

typedef struct _DaemonConfigurationServerConfiguration DaemonConfigurationServerConfiguration;
typedef struct _DaemonConfigurationServerConfigurationClass DaemonConfigurationServerConfigurationClass;

#define DAEMON_IRC_TYPE_COMMAND (daemon_irc_command_get_type ())
#define DAEMON_IRC_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_IRC_TYPE_COMMAND, DaemonIRCCommand))
#define DAEMON_IRC_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_IRC_TYPE_COMMAND, DaemonIRCCommandClass))
#define DAEMON_IRC_IS_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_IRC_TYPE_COMMAND))
#define DAEMON_IRC_IS_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_IRC_TYPE_COMMAND))
#define DAEMON_IRC_COMMAND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_IRC_TYPE_COMMAND, DaemonIRCCommandClass))

typedef struct _DaemonIRCCommand DaemonIRCCommand;
typedef struct _DaemonIRCCommandClass DaemonIRCCommandClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_io_channel_unref0(var) ((var == NULL) ? NULL : (var = (g_io_channel_unref (var), NULL)))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define DAEMON_TYPE_CONSOLE_COLORS (daemon_console_colors_get_type ())

#define DAEMON_IRC_TYPE_COMMAND_TYPES (daemon_irc_command_types_get_type ())

#define DAEMON_IRC_TYPE_ENTITY (daemon_irc_entity_get_type ())
#define DAEMON_IRC_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_IRC_TYPE_ENTITY, DaemonIRCEntity))
#define DAEMON_IRC_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_IRC_TYPE_ENTITY, DaemonIRCEntityClass))
#define DAEMON_IRC_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_IRC_TYPE_ENTITY))
#define DAEMON_IRC_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_IRC_TYPE_ENTITY))
#define DAEMON_IRC_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_IRC_TYPE_ENTITY, DaemonIRCEntityClass))

typedef struct _DaemonIRCEntity DaemonIRCEntity;
typedef struct _DaemonIRCEntityClass DaemonIRCEntityClass;

#define DAEMON_IRC_TYPE_CODES (daemon_irc_codes_get_type ())

#define DAEMON_EVENTS_TYPE_LOG_EVENT (daemon_events_log_event_get_type ())
#define DAEMON_EVENTS_LOG_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEvent))
#define DAEMON_EVENTS_LOG_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEventClass))
#define DAEMON_EVENTS_IS_LOG_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT))
#define DAEMON_EVENTS_IS_LOG_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_EVENTS_TYPE_LOG_EVENT))
#define DAEMON_EVENTS_LOG_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEventClass))

typedef struct _DaemonEventsLogEvent DaemonEventsLogEvent;
typedef struct _DaemonEventsLogEventClass DaemonEventsLogEventClass;

#define DAEMON_EVENTS_TYPE_MESSAGE_EVENT (daemon_events_message_event_get_type ())
#define DAEMON_EVENTS_MESSAGE_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_EVENTS_TYPE_MESSAGE_EVENT, DaemonEventsMessageEvent))
#define DAEMON_EVENTS_MESSAGE_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_EVENTS_TYPE_MESSAGE_EVENT, DaemonEventsMessageEventClass))
#define DAEMON_EVENTS_IS_MESSAGE_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_EVENTS_TYPE_MESSAGE_EVENT))
#define DAEMON_EVENTS_IS_MESSAGE_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_EVENTS_TYPE_MESSAGE_EVENT))
#define DAEMON_EVENTS_MESSAGE_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_EVENTS_TYPE_MESSAGE_EVENT, DaemonEventsMessageEventClass))

typedef struct _DaemonEventsMessageEvent DaemonEventsMessageEvent;
typedef struct _DaemonEventsMessageEventClass DaemonEventsMessageEventClass;

#define DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT (daemon_events_change_name_event_get_type ())
#define DAEMON_EVENTS_CHANGE_NAME_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, DaemonEventsChangeNameEvent))
#define DAEMON_EVENTS_CHANGE_NAME_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, DaemonEventsChangeNameEventClass))
#define DAEMON_EVENTS_IS_CHANGE_NAME_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT))
#define DAEMON_EVENTS_IS_CHANGE_NAME_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT))
#define DAEMON_EVENTS_CHANGE_NAME_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, DaemonEventsChangeNameEventClass))

typedef struct _DaemonEventsChangeNameEvent DaemonEventsChangeNameEvent;
typedef struct _DaemonEventsChangeNameEventClass DaemonEventsChangeNameEventClass;

#define DAEMON_EVENTS_TYPE_STATUS_CHANGE (daemon_events_status_change_get_type ())

#define DAEMON_EVENTS_TYPE_STATUS_EVENT (daemon_events_status_event_get_type ())
#define DAEMON_EVENTS_STATUS_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_EVENTS_TYPE_STATUS_EVENT, DaemonEventsStatusEvent))
#define DAEMON_EVENTS_STATUS_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_EVENTS_TYPE_STATUS_EVENT, DaemonEventsStatusEventClass))
#define DAEMON_EVENTS_IS_STATUS_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_EVENTS_TYPE_STATUS_EVENT))
#define DAEMON_EVENTS_IS_STATUS_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_EVENTS_TYPE_STATUS_EVENT))
#define DAEMON_EVENTS_STATUS_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_EVENTS_TYPE_STATUS_EVENT, DaemonEventsStatusEventClass))

typedef struct _DaemonEventsStatusEvent DaemonEventsStatusEvent;
typedef struct _DaemonEventsStatusEventClass DaemonEventsStatusEventClass;

#define DAEMON_DATA_TYPE_IDATA_ACCESS (daemon_data_idata_access_get_type ())
#define DAEMON_DATA_IDATA_ACCESS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_DATA_TYPE_IDATA_ACCESS, DaemonDataIDataAccess))
#define DAEMON_DATA_IS_IDATA_ACCESS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_DATA_TYPE_IDATA_ACCESS))
#define DAEMON_DATA_IDATA_ACCESS_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), DAEMON_DATA_TYPE_IDATA_ACCESS, DaemonDataIDataAccessIface))

typedef struct _DaemonDataIDataAccess DaemonDataIDataAccess;
typedef struct _DaemonDataIDataAccessIface DaemonDataIDataAccessIface;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

#define DAEMON_TYPE_EMAIL_SENDER (daemon_email_sender_get_type ())
#define DAEMON_EMAIL_SENDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_TYPE_EMAIL_SENDER, DaemonEmailSender))
#define DAEMON_EMAIL_SENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_TYPE_EMAIL_SENDER, DaemonEmailSenderClass))
#define DAEMON_IS_EMAIL_SENDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_TYPE_EMAIL_SENDER))
#define DAEMON_IS_EMAIL_SENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_TYPE_EMAIL_SENDER))
#define DAEMON_EMAIL_SENDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_TYPE_EMAIL_SENDER, DaemonEmailSenderClass))

typedef struct _DaemonEmailSender DaemonEmailSender;
typedef struct _DaemonEmailSenderClass DaemonEmailSenderClass;
#define _daemon_email_sender_unref0(var) ((var == NULL) ? NULL : (var = (daemon_email_sender_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

typedef enum  {
	DAEMON_IRC_IRC_ERROR_InvalidHost,
	DAEMON_IRC_IRC_ERROR_DNSError
} DaemonIRCIRCError;
#define DAEMON_IRC_IRC_ERROR daemon_irc_irc_error_quark ()
struct _DaemonIRCIRCConnection {
	GObject parent_instance;
	DaemonIRCIRCConnectionPrivate * priv;
};

struct _DaemonIRCIRCConnectionClass {
	GObjectClass parent_class;
};

struct _DaemonIRCIRCConnectionPrivate {
	GSocketClient* _connection;
	DaemonConfigurationServerConfiguration* _ServerConfiguration;
	gchar* _Host;
	guint16 _Port;
	GInetAddress* _Address;
	GInetSocketAddress* _Endpoint;
	GSocketConnection* _socket;
	GDataInputStream* _inputStream;
	GIOChannel* _channel;
	GList* _channels;
	GList* _pendingChannels;
	gint _lastFd;
	GList* _waitingCommands;
	gint _nickIndex;
	gchar* _nickSuffix;
	gchar* _lastNick;
	gchar* _currentNick;
	gboolean _authComplete;
};

typedef enum  {
	DAEMON_CONSOLE_COLORS_Red = 31,
	DAEMON_CONSOLE_COLORS_Green = 32,
	DAEMON_CONSOLE_COLORS_Yellow = 33,
	DAEMON_CONSOLE_COLORS_Blue = 34,
	DAEMON_CONSOLE_COLORS_Purple = 35,
	DAEMON_CONSOLE_COLORS_Cyan = 36,
	DAEMON_CONSOLE_COLORS_White = 37
} DaemonConsoleColors;

typedef enum  {
	DAEMON_IRC_COMMAND_ERROR_Invalid
} DaemonIRCCommandError;
#define DAEMON_IRC_COMMAND_ERROR daemon_irc_command_error_quark ()
typedef enum  {
	DAEMON_IRC_COMMAND_TYPES_Invalid,
	DAEMON_IRC_COMMAND_TYPES_User,
	DAEMON_IRC_COMMAND_TYPES_Nick,
	DAEMON_IRC_COMMAND_TYPES_PrivMsg,
	DAEMON_IRC_COMMAND_TYPES_Pass,
	DAEMON_IRC_COMMAND_TYPES_Server,
	DAEMON_IRC_COMMAND_TYPES_Oper,
	DAEMON_IRC_COMMAND_TYPES_Quit,
	DAEMON_IRC_COMMAND_TYPES_SQuit,
	DAEMON_IRC_COMMAND_TYPES_Join,
	DAEMON_IRC_COMMAND_TYPES_Part,
	DAEMON_IRC_COMMAND_TYPES_Mode,
	DAEMON_IRC_COMMAND_TYPES_Topic,
	DAEMON_IRC_COMMAND_TYPES_Names,
	DAEMON_IRC_COMMAND_TYPES_List,
	DAEMON_IRC_COMMAND_TYPES_Invite,
	DAEMON_IRC_COMMAND_TYPES_Kick,
	DAEMON_IRC_COMMAND_TYPES_Version,
	DAEMON_IRC_COMMAND_TYPES_Stats,
	DAEMON_IRC_COMMAND_TYPES_Links,
	DAEMON_IRC_COMMAND_TYPES_Time,
	DAEMON_IRC_COMMAND_TYPES_Connect,
	DAEMON_IRC_COMMAND_TYPES_Trace,
	DAEMON_IRC_COMMAND_TYPES_Admin,
	DAEMON_IRC_COMMAND_TYPES_Info,
	DAEMON_IRC_COMMAND_TYPES_Notice,
	DAEMON_IRC_COMMAND_TYPES_Who,
	DAEMON_IRC_COMMAND_TYPES_WhoIs,
	DAEMON_IRC_COMMAND_TYPES_WhoWas,
	DAEMON_IRC_COMMAND_TYPES_Kill,
	DAEMON_IRC_COMMAND_TYPES_Ping,
	DAEMON_IRC_COMMAND_TYPES_Pong,
	DAEMON_IRC_COMMAND_TYPES_Error
} DaemonIRCCommandTypes;

typedef enum  {
	DAEMON_IRC_CODES_Invalid = -1,
	DAEMON_IRC_CODES_NoSuckNick = 401,
	DAEMON_IRC_CODES_NoSuchServer = 402,
	DAEMON_IRC_CODES_NoSuchChannel = 403,
	DAEMON_IRC_CODES_CannotSendToChannel = 404,
	DAEMON_IRC_CODES_TooManyChannels = 405,
	DAEMON_IRC_CODES_WasNoSuckNick = 406,
	DAEMON_IRC_CODES_TooManyTargets = 407,
	DAEMON_IRC_CODES_NoOrigin = 409,
	DAEMON_IRC_CODES_NoRecipient = 411,
	DAEMON_IRC_CODES_NoTextToSend = 412,
	DAEMON_IRC_CODES_NoTopLevel = 413,
	DAEMON_IRC_CODES_WildTopLevel = 414,
	DAEMON_IRC_CODES_UnknownCommand = 421,
	DAEMON_IRC_CODES_NoMOTD = 422,
	DAEMON_IRC_CODES_NoAdminInfo = 423,
	DAEMON_IRC_CODES_FileError = 424,
	DAEMON_IRC_CODES_NoNicknameGiven = 431,
	DAEMON_IRC_CODES_ErroneusNickname = 432,
	DAEMON_IRC_CODES_NicknameInUse = 433,
	DAEMON_IRC_CODES_NickCollision = 436,
	DAEMON_IRC_CODES_UserNotInChannel = 441,
	DAEMON_IRC_CODES_NotOnChannel = 442,
	DAEMON_IRC_CODES_UserOnChannel = 443,
	DAEMON_IRC_CODES_NoLogin = 444,
	DAEMON_IRC_CODES_SummonDisabled = 445,
	DAEMON_IRC_CODES_UserDisabled = 446,
	DAEMON_IRC_CODES_NotRegistered = 451,
	DAEMON_IRC_CODES_NeedMoreParameters = 461,
	DAEMON_IRC_CODES_AlreadyRegistered = 462,
	DAEMON_IRC_CODES_NoPermissionForHost = 463,
	DAEMON_IRC_CODES_PasswordMismatch = 464,
	DAEMON_IRC_CODES_BannedFromServer = 465,
	DAEMON_IRC_CODES_KeySet = 467,
	DAEMON_IRC_CODES_ChannelIsFull = 471,
	DAEMON_IRC_CODES_UnknownMode = 472,
	DAEMON_IRC_CODES_InviteOnlyChannel = 473,
	DAEMON_IRC_CODES_BannedFromChannel = 474,
	DAEMON_IRC_CODES_BadChannelKey = 475,
	DAEMON_IRC_CODES_PermissionDenied = 481,
	DAEMON_IRC_CODES_ChannelOperatorPrivilegesNeeded = 482,
	DAEMON_IRC_CODES_CannotKillServer = 483,
	DAEMON_IRC_CODES_NoOperatorHost = 491,
	DAEMON_IRC_CODES_UnknownModeFlag = 501,
	DAEMON_IRC_CODES_UsersDontMatch = 502,
	DAEMON_IRC_CODES_None = 300,
	DAEMON_IRC_CODES_Away = 301,
	DAEMON_IRC_CODES_UserHost = 302,
	DAEMON_IRC_CODES_Ison = 303,
	DAEMON_IRC_CODES_UnAway = 305,
	DAEMON_IRC_CODES_NoAway = 306,
	DAEMON_IRC_CODES_WhoIsUser = 311,
	DAEMON_IRC_CODES_WhoIsServer = 312,
	DAEMON_IRC_CODES_WhoIsOperator = 313,
	DAEMON_IRC_CODES_WhoIsIdle = 317,
	DAEMON_IRC_CODES_EndOfWhoIs = 318,
	DAEMON_IRC_CODES_WhoIsChannels = 319,
	DAEMON_IRC_CODES_WhoWasUser = 314,
	DAEMON_IRC_CODES_EndOfWhoWas = 369,
	DAEMON_IRC_CODES_ListStart = 321,
	DAEMON_IRC_CODES_List = 322,
	DAEMON_IRC_CODES_ListEnd = 323,
	DAEMON_IRC_CODES_ChannelModeIs = 324,
	DAEMON_IRC_CODES_NoTopic = 331,
	DAEMON_IRC_CODES_Topic = 332,
	DAEMON_IRC_CODES_Inviting = 341,
	DAEMON_IRC_CODES_Summoning = 342,
	DAEMON_IRC_CODES_Version = 351,
	DAEMON_IRC_CODES_WhoReply = 352,
	DAEMON_IRC_CODES_EndOfWho = 315,
	DAEMON_IRC_CODES_NameReply = 353,
	DAEMON_IRC_CODES_EndOfNames = 366,
	DAEMON_IRC_CODES_Links = 364,
	DAEMON_IRC_CODES_EndOfLinks = 365,
	DAEMON_IRC_CODES_BanList = 367,
	DAEMON_IRC_CODES_EndOfBanList = 368,
	DAEMON_IRC_CODES_Info = 371,
	DAEMON_IRC_CODES_EndOfInfo = 374,
	DAEMON_IRC_CODES_MOTDStart = 375,
	DAEMON_IRC_CODES_MOTD = 372,
	DAEMON_IRC_CODES_EndOfMOTD = 376,
	DAEMON_IRC_CODES_YoureOperator = 381,
	DAEMON_IRC_CODES_Rehasing = 382,
	DAEMON_IRC_CODES_Time = 391,
	DAEMON_IRC_CODES_UsersStart = 392,
	DAEMON_IRC_CODES_Users = 393,
	DAEMON_IRC_CODES_EndOfUsers = 394,
	DAEMON_IRC_CODES_NoUsers = 395,
	DAEMON_IRC_CODES_TraceLink = 200,
	DAEMON_IRC_CODES_TraceConnecting = 201,
	DAEMON_IRC_CODES_TraceHandshake = 202,
	DAEMON_IRC_CODES_TraceUnknown = 203,
	DAEMON_IRC_CODES_TraceOperator = 204,
	DAEMON_IRC_CODES_TraceUser = 205,
	DAEMON_IRC_CODES_TraceServer = 206,
	DAEMON_IRC_CODES_TraceNewType = 208,
	DAEMON_IRC_CODES_TraceLog = 261,
	DAEMON_IRC_CODES_StatsLinkInfo = 211,
	DAEMON_IRC_CODES_StatsCommands = 212,
	DAEMON_IRC_CODES_StatsCLine = 213,
	DAEMON_IRC_CODES_StatsNLine = 214,
	DAEMON_IRC_CODES_StatsSILine = 215,
	DAEMON_IRC_CODES_StatsKLine = 216,
	DAEMON_IRC_CODES_StatsYLine = 218,
	DAEMON_IRC_CODES_EndOfStats = 219,
	DAEMON_IRC_CODES_StatsSLineReply = 241,
	DAEMON_IRC_CODES_StatsUptime = 242,
	DAEMON_IRC_CODES_StatsOLine = 243,
	DAEMON_IRC_CODES_StatsHLine = 244,
	DAEMON_IRC_CODES_UserModeIs = 221,
	DAEMON_IRC_CODES_LUserClient = 251,
	DAEMON_IRC_CODES_OperatorsOnline = 252,
	DAEMON_IRC_CODES_UnknownUsers = 253,
	DAEMON_IRC_CODES_UserChannels = 254,
	DAEMON_IRC_CODES_UserMe = 255,
	DAEMON_IRC_CODES_AdminMe = 256,
	DAEMON_IRC_CODES_AdminLoc1 = 257,
	DAEMON_IRC_CODES_AdminLoc2 = 258,
	DAEMON_IRC_CODES_AdminEmail = 259
} DaemonIRCCodes;

typedef enum  {
	DAEMON_DATA_DATA_ACCESS_ERROR_OpenFailed,
	DAEMON_DATA_DATA_ACCESS_ERROR_WriteError,
	DAEMON_DATA_DATA_ACCESS_ERROR_ReadError
} DaemonDataDataAccessError;
#define DAEMON_DATA_DATA_ACCESS_ERROR daemon_data_data_access_error_quark ()
typedef enum  {
	DAEMON_EVENTS_STATUS_CHANGE_Join,
	DAEMON_EVENTS_STATUS_CHANGE_Leave
} DaemonEventsStatusChange;

struct _DaemonDataIDataAccessIface {
	GTypeInterface parent_iface;
	void (*Log) (DaemonDataIDataAccess* self, DaemonEventsLogEvent* event, GError** error);
	GDateTime* (*UserLastSeen) (DaemonDataIDataAccess* self, const gchar* username, const gchar* channel, const gchar* server, GError** error);
	GList* (*GetLog) (DaemonDataIDataAccess* self, const gchar* channel, const gchar* server, GError** error);
	void (*Init) (DaemonDataIDataAccess* self, const gchar* logPath, GError** error);
};

typedef enum  {
	DAEMON_EMAIL_ERROR_ServerFailed,
	DAEMON_EMAIL_ERROR_DNSError
} DaemonEmailError;
#define DAEMON_EMAIL_ERROR daemon_email_error_quark ()

static gpointer daemon_irc_irc_connection_parent_class = NULL;
static gchar* daemon_irc_irc_connection__RealName;
static gchar* daemon_irc_irc_connection__RealName = NULL;
static gchar** daemon_irc_irc_connection__Nicknames;
static gint daemon_irc_irc_connection__Nicknames_length1;
static gchar** daemon_irc_irc_connection__Nicknames = NULL;
static gint daemon_irc_irc_connection__Nicknames_length1 = 0;
static gint _daemon_irc_irc_connection__Nicknames_size_ = 0;
static gchar* daemon_irc_irc_connection__Hostname;
static gchar* daemon_irc_irc_connection__Hostname = NULL;
static gchar* daemon_irc_irc_connection__Username;
static gchar* daemon_irc_irc_connection__Username = NULL;

GQuark daemon_irc_irc_error_quark (void);
GType daemon_irc_irc_connection_get_type (void) G_GNUC_CONST;
GType daemon_configuration_server_configuration_get_type (void) G_GNUC_CONST;
GType daemon_irc_command_get_type (void) G_GNUC_CONST;
#define DAEMON_IRC_IRC_CONNECTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DAEMON_IRC_TYPE_IRC_CONNECTION, DaemonIRCIRCConnectionPrivate))
enum  {
	DAEMON_IRC_IRC_CONNECTION_DUMMY_PROPERTY,
	DAEMON_IRC_IRC_CONNECTION_SERVER_CONFIGURATION,
	DAEMON_IRC_IRC_CONNECTION_HOST,
	DAEMON_IRC_IRC_CONNECTION_ADDRESS,
	DAEMON_IRC_IRC_CONNECTION_ENDPOINT
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
#define DAEMON_IRC_IRC_CONNECTION__reconnectTime 5
#define DAEMON_IRC_IRC_CONNECTION__helpString "This bot can only understand the following Commands:\n" \
"\t\tLASTSEEN <CHANNEL> <USERNAME>\n" \
"\t\tSENDLOG <CHANNEL> <EMAIL>"
DaemonIRCIRCConnection* daemon_irc_irc_connection_new (DaemonConfigurationServerConfiguration* configuration, GError** error);
DaemonIRCIRCConnection* daemon_irc_irc_connection_construct (GType object_type, DaemonConfigurationServerConfiguration* configuration, GError** error);
static void daemon_irc_irc_connection_set_ServerConfiguration (DaemonIRCIRCConnection* self, DaemonConfigurationServerConfiguration* value);
const gchar* daemon_configuration_server_configuration_get_Host (DaemonConfigurationServerConfiguration* self);
static void daemon_irc_irc_connection_set_Address (DaemonIRCIRCConnection* self, GInetAddress* value);
GInetAddress* daemon_irc_irc_connection_get_Address (DaemonIRCIRCConnection* self);
guint16 daemon_configuration_server_configuration_get_Port (DaemonConfigurationServerConfiguration* self);
static void daemon_irc_irc_connection_set_Endpoint (DaemonIRCIRCConnection* self, GInetSocketAddress* value);
static void daemon_irc_irc_connection_Connect (DaemonIRCIRCConnection* self);
GInetSocketAddress* daemon_irc_irc_connection_get_Endpoint (DaemonIRCIRCConnection* self);
void daemon_global_log_Warning (const gchar* format, ...);
DaemonConfigurationServerConfiguration* daemon_irc_irc_connection_get_ServerConfiguration (DaemonIRCIRCConnection* self);
const gchar* daemon_configuration_server_configuration_get_Name (DaemonConfigurationServerConfiguration* self);
static void daemon_irc_irc_connection_Reconnect (DaemonIRCIRCConnection* self, gint wait);
static void daemon_irc_irc_connection_Connected (DaemonIRCIRCConnection* self);
gboolean daemon_irc_irc_connection_InputWatch (DaemonIRCIRCConnection* self, GIOChannel* source, GIOCondition condition);
static gboolean _daemon_irc_irc_connection_InputWatch_gio_func (GIOChannel* source, GIOCondition condition, gpointer self);
GType daemon_console_colors_get_type (void) G_GNUC_CONST;
void daemon_global_log_ColorMessage (DaemonConsoleColors color, const gchar* format, ...);
static void daemon_irc_irc_connection_SendNickname (DaemonIRCIRCConnection* self);
static void daemon_irc_irc_connection_Auth (DaemonIRCIRCConnection* self);
static void daemon_irc_irc_connection_Disconnected (DaemonIRCIRCConnection* self);
static void daemon_irc_irc_connection_SendCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command);
gchar* daemon_irc_command_Prepare (DaemonIRCCommand* self);
gchar* daemon_irc_command_ToString (DaemonIRCCommand* self);
static void daemon_irc_irc_connection_QueueCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command);
static void daemon_irc_irc_connection_Receive (DaemonIRCIRCConnection* self, GIOChannel* source);
GQuark daemon_irc_command_error_quark (void);
DaemonIRCCommand* daemon_irc_command_Parse (const gchar* text, GError** error);
static void daemon_irc_irc_connection_ReceivedCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command);
void daemon_global_log_Error (const gchar* format, ...);
gchar** daemon_irc_irc_connection_get_Nicknames (int* result_length1);
GType daemon_irc_command_types_get_type (void) G_GNUC_CONST;
DaemonIRCCommand* daemon_irc_command_new (DaemonIRCCommandTypes type, gchar** parameters, int parameters_length1);
DaemonIRCCommand* daemon_irc_command_construct (GType object_type, DaemonIRCCommandTypes type, gchar** parameters, int parameters_length1);
const gchar* daemon_irc_irc_connection_get_Username (void);
const gchar* daemon_irc_irc_connection_get_Hostname (void);
const gchar* daemon_irc_irc_connection_get_RealName (void);
static void daemon_irc_irc_connection_JoinChannel (DaemonIRCIRCConnection* self, const gchar* name);
GType daemon_irc_entity_get_type (void) G_GNUC_CONST;
static void daemon_irc_irc_connection_SendMessage (DaemonIRCIRCConnection* self, DaemonIRCEntity* target, const gchar* format, ...);
const gchar* daemon_irc_entity_get_Name (DaemonIRCEntity* self);
GType daemon_irc_codes_get_type (void) G_GNUC_CONST;
DaemonIRCCodes daemon_irc_command_get_Code (DaemonIRCCommand* self);
static void daemon_irc_irc_connection_ProcessCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command);
static void daemon_irc_irc_connection_ProcessCode (DaemonIRCIRCConnection* self, DaemonIRCCommand* command);
gchar** daemon_configuration_server_configuration_get_Channels (DaemonConfigurationServerConfiguration* self, int* result_length1);
static gboolean daemon_irc_irc_connection_InChannel (DaemonIRCIRCConnection* self, const gchar* name);
static gboolean daemon_irc_irc_connection_IsChannelPending (DaemonIRCIRCConnection* self, const gchar* name);
DaemonIRCCommandTypes daemon_irc_command_get_Type (DaemonIRCCommand* self);
DaemonIRCEntity** daemon_irc_command_get_Receivers (DaemonIRCCommand* self, int* result_length1);
static void daemon_irc_irc_connection_ProcessMessage (DaemonIRCIRCConnection* self, DaemonIRCEntity* sender, const gchar* message);
DaemonIRCEntity* daemon_irc_command_get_Sender (DaemonIRCCommand* self);
gchar** daemon_irc_command_get_Parameters (DaemonIRCCommand* self, int* result_length1);
GType daemon_events_log_event_get_type (void) G_GNUC_CONST;
GQuark daemon_data_data_access_error_quark (void);
void daemon_data_irc_log_Log (DaemonEventsLogEvent* event, GError** error);
DaemonEventsMessageEvent* daemon_events_message_event_new (const gchar* username, const gchar* message, const gchar* channel, const gchar* server);
DaemonEventsMessageEvent* daemon_events_message_event_construct (GType object_type, const gchar* username, const gchar* message, const gchar* channel, const gchar* server);
GType daemon_events_message_event_get_type (void) G_GNUC_CONST;
DaemonIRCEntity* daemon_irc_command_get_Receiver (DaemonIRCCommand* self);
DaemonEventsChangeNameEvent* daemon_events_change_name_event_new (const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server);
DaemonEventsChangeNameEvent* daemon_events_change_name_event_construct (GType object_type, const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server);
GType daemon_events_change_name_event_get_type (void) G_GNUC_CONST;
GType daemon_events_status_change_get_type (void) G_GNUC_CONST;
DaemonEventsStatusEvent* daemon_events_status_event_new (const gchar* username, DaemonEventsStatusChange type, const gchar* channel, const gchar* server);
DaemonEventsStatusEvent* daemon_events_status_event_construct (GType object_type, const gchar* username, DaemonEventsStatusChange type, const gchar* channel, const gchar* server);
GType daemon_events_status_event_get_type (void) G_GNUC_CONST;
static void daemon_irc_irc_connection_SendUnavailable (DaemonIRCIRCConnection* self, DaemonIRCEntity* receiver);
GType daemon_data_idata_access_get_type (void) G_GNUC_CONST;
DaemonDataIDataAccess* daemon_plugin_manager_get_DataAccess (void);
GDateTime* daemon_data_idata_access_UserLastSeen (DaemonDataIDataAccess* self, const gchar* username, const gchar* channel, const gchar* server, GError** error);
GList* daemon_data_idata_access_GetLog (DaemonDataIDataAccess* self, const gchar* channel, const gchar* server, GError** error);
gchar* daemon_events_log_event_ToString (DaemonEventsLogEvent* self);
DaemonEmailSender* daemon_email_sender_new (void);
DaemonEmailSender* daemon_email_sender_construct (GType object_type);
gpointer daemon_email_sender_ref (gpointer instance);
void daemon_email_sender_unref (gpointer instance);
GParamSpec* daemon_param_spec_email_sender (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void daemon_value_set_email_sender (GValue* value, gpointer v_object);
void daemon_value_take_email_sender (GValue* value, gpointer v_object);
gpointer daemon_value_get_email_sender (const GValue* value);
GType daemon_email_sender_get_type (void) G_GNUC_CONST;
GQuark daemon_email_error_quark (void);
void daemon_email_sender_SendEmail (DaemonEmailSender* self, const gchar* receiver, const gchar* subject, const gchar* body, GError** error);
static void daemon_irc_irc_connection_NotUnderstood (DaemonIRCIRCConnection* self, DaemonIRCEntity* sender);
void daemon_irc_irc_connection_set_RealName (const gchar* value);
void daemon_irc_irc_connection_set_Nicknames (gchar** value, int value_length1);
static gchar** _vala_array_dup4 (gchar** self, int length);
void daemon_irc_irc_connection_set_Hostname (const gchar* value);
void daemon_irc_irc_connection_set_Username (const gchar* value);
const gchar* daemon_irc_irc_connection_get_Host (DaemonIRCIRCConnection* self);
static void daemon_irc_irc_connection_set_Host (DaemonIRCIRCConnection* self, const gchar* value);
guint16 daemon_irc_irc_connection_get_Port (DaemonIRCIRCConnection* self);
static void daemon_irc_irc_connection_set_Port (DaemonIRCIRCConnection* self, guint16 value);
static void daemon_irc_irc_connection_finalize (GObject* obj);
static void _vala_daemon_irc_irc_connection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_daemon_irc_irc_connection_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


GQuark daemon_irc_irc_error_quark (void) {
	return g_quark_from_static_string ("daemon_irc_irc_error-quark");
}


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


DaemonIRCIRCConnection* daemon_irc_irc_connection_construct (GType object_type, DaemonConfigurationServerConfiguration* configuration, GError** error) {
	DaemonIRCIRCConnection * self = NULL;
	GResolver* _tmp0_ = NULL;
	GResolver* _tmp1_;
	GResolver* resolver;
	GList* addresses = NULL;
	const gchar* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
	GList* _tmp4_;
	guint _tmp6_;
	gconstpointer _tmp12_ = NULL;
	guint16 _tmp13_;
	GInetSocketAddress* _tmp14_ = NULL;
	GInetSocketAddress* _tmp15_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (configuration != NULL, NULL);
	self = (DaemonIRCIRCConnection*) g_object_new (object_type, NULL);
	daemon_irc_irc_connection_set_ServerConfiguration (self, configuration);
	_tmp0_ = g_resolver_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	resolver = _tmp1_;
	_tmp2_ = daemon_configuration_server_configuration_get_Host (configuration);
	_tmp3_ = g_resolver_lookup_by_name (resolver, _tmp2_, NULL, &_inner_error_);
	_tmp4_ = _tmp3_;
	if (_inner_error_ != NULL) {
		goto __catch9_g_error;
	}
	__g_list_free__g_object_unref0_0 (addresses);
	addresses = _tmp4_;
	goto __finally9;
	__catch9_g_error:
	{
		GError * _error_;
		GError* _tmp5_ = NULL;
		_error_ = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = g_error_new_literal (DAEMON_IRC_IRC_ERROR, DAEMON_IRC_IRC_ERROR_DNSError, _error_->message);
		_inner_error_ = _tmp5_;
		_g_error_free0 (_error_);
		goto __finally9;
	}
	__finally9:
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == DAEMON_IRC_IRC_ERROR) {
			g_propagate_error (error, _inner_error_);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (self);
			return NULL;
		} else {
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp6_ = g_list_length (addresses);
	if (_tmp6_ == 0) {
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		gchar* _tmp9_;
		GError* _tmp10_ = NULL;
		GError* _tmp11_;
		_tmp7_ = daemon_configuration_server_configuration_get_Host (configuration);
		_tmp8_ = g_strconcat ("No IP found for ", _tmp7_, NULL);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_error_new_literal (DAEMON_IRC_IRC_ERROR, DAEMON_IRC_IRC_ERROR_DNSError, _tmp9_);
		_tmp11_ = _tmp10_;
		_g_free0 (_tmp9_);
		_inner_error_ = _tmp11_;
		if (_inner_error_->domain == DAEMON_IRC_IRC_ERROR) {
			g_propagate_error (error, _inner_error_);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (self);
			return NULL;
		} else {
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp12_ = g_list_nth_data (addresses, (guint) 0);
	daemon_irc_irc_connection_set_Address (self, (GInetAddress*) _tmp12_);
	_tmp13_ = daemon_configuration_server_configuration_get_Port (configuration);
	_tmp14_ = (GInetSocketAddress*) g_inet_socket_address_new (self->priv->_Address, _tmp13_);
	_tmp15_ = _tmp14_;
	daemon_irc_irc_connection_set_Endpoint (self, _tmp15_);
	_g_object_unref0 (_tmp15_);
	daemon_irc_irc_connection_Connect (self);
	__g_list_free__g_object_unref0_0 (addresses);
	_g_object_unref0 (resolver);
	return self;
}


DaemonIRCIRCConnection* daemon_irc_irc_connection_new (DaemonConfigurationServerConfiguration* configuration, GError** error) {
	return daemon_irc_irc_connection_construct (DAEMON_IRC_TYPE_IRC_CONNECTION, configuration, error);
}


static gboolean _daemon_irc_irc_connection_InputWatch_gio_func (GIOChannel* source, GIOCondition condition, gpointer self) {
	gboolean result;
	result = daemon_irc_irc_connection_InputWatch (self, source, condition);
	return result;
}


static void daemon_irc_irc_connection_Connect (DaemonIRCIRCConnection* self) {
	gchar* _tmp0_;
	GSocketClient* _tmp1_ = NULL;
	GSocketConnection* _tmp2_ = NULL;
	GSocketConnection* _tmp3_;
	GSocketConnection* _tmp4_;
	GInputStream* _tmp5_ = NULL;
	GDataInputStream* _tmp6_ = NULL;
	GSocket* _tmp8_ = NULL;
	GSocket* _tmp9_ = NULL;
	gint _tmp10_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	self->priv->_authComplete = FALSE;
	self->priv->_nickIndex = 0;
	_tmp0_ = g_strdup ("");
	_g_free0 (self->priv->_nickSuffix);
	self->priv->_nickSuffix = _tmp0_;
	_g_free0 (self->priv->_currentNick);
	self->priv->_currentNick = NULL;
	_g_free0 (self->priv->_lastNick);
	self->priv->_lastNick = NULL;
	__g_list_free__g_free0_0 (self->priv->_channels);
	self->priv->_channels = NULL;
	__g_list_free__g_free0_0 (self->priv->_pendingChannels);
	self->priv->_pendingChannels = NULL;
	_tmp1_ = g_socket_client_new ();
	_g_object_unref0 (self->priv->_connection);
	self->priv->_connection = _tmp1_;
	g_socket_client_set_protocol (self->priv->_connection, G_SOCKET_PROTOCOL_TCP);
	g_socket_client_set_timeout (self->priv->_connection, (guint) 60);
	_tmp2_ = g_socket_client_connect (self->priv->_connection, (GSocketConnectable*) self->priv->_Endpoint, NULL, &_inner_error_);
	_tmp3_ = _tmp2_;
	if (_inner_error_ != NULL) {
		goto __catch10_g_error;
	}
	_tmp4_ = _g_object_ref0 (_tmp3_);
	_g_object_unref0 (self->priv->_socket);
	self->priv->_socket = _tmp4_;
	_tmp5_ = g_io_stream_get_input_stream ((GIOStream*) self->priv->_socket);
	_tmp6_ = g_data_input_stream_new (_tmp5_);
	_g_object_unref0 (self->priv->_inputStream);
	self->priv->_inputStream = _tmp6_;
	goto __finally10;
	__catch10_g_error:
	{
		const gchar* _tmp7_ = NULL;
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
		_tmp7_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
		daemon_global_log_Warning ("Failed to connect to Server %s", _tmp7_);
		daemon_irc_irc_connection_Reconnect (self, DAEMON_IRC_IRC_CONNECTION__reconnectTime);
		return;
	}
	__finally10:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = g_socket_connection_get_socket (self->priv->_socket);
	g_socket_set_keepalive (_tmp8_, TRUE);
	daemon_irc_irc_connection_Connected (self);
	_tmp9_ = g_socket_connection_get_socket (self->priv->_socket);
	_tmp10_ = g_socket_get_fd (_tmp9_);
	if (_tmp10_ != self->priv->_lastFd) {
		GSocket* _tmp11_ = NULL;
		gint _tmp12_;
		GSocket* _tmp13_ = NULL;
		gint _tmp14_;
		GIOChannel* _tmp15_ = NULL;
		_tmp11_ = g_socket_connection_get_socket (self->priv->_socket);
		_tmp12_ = g_socket_get_fd (_tmp11_);
		self->priv->_lastFd = _tmp12_;
		if (self->priv->_channel != NULL) {
			g_io_channel_shutdown (self->priv->_channel, FALSE, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch11_g_error;
			}
			goto __finally11;
			__catch11_g_error:
			{
				g_clear_error (&_inner_error_);
				_inner_error_ = NULL;
			}
			__finally11:
			if (_inner_error_ != NULL) {
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			_g_io_channel_unref0 (self->priv->_channel);
			self->priv->_channel = NULL;
		}
		_tmp13_ = g_socket_connection_get_socket (self->priv->_socket);
		_tmp14_ = g_socket_get_fd (_tmp13_);
		_tmp15_ = g_io_channel_unix_new (_tmp14_);
		_g_io_channel_unref0 (self->priv->_channel);
		self->priv->_channel = _tmp15_;
		g_io_add_watch (self->priv->_channel, ((((G_IO_IN | G_IO_OUT) | G_IO_HUP) | G_IO_ERR) | G_IO_PRI) | G_IO_NVAL, _daemon_irc_irc_connection_InputWatch_gio_func, self);
		g_io_channel_init (self->priv->_channel);
	}
}


static void daemon_irc_irc_connection_Reconnect (DaemonIRCIRCConnection* self, gint wait) {
	const gchar* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_usleep ((gulong) (wait * 1000000));
	_tmp0_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
	daemon_global_log_Warning ("Trying to reconnect to Server %s", _tmp0_);
	daemon_irc_irc_connection_Connect (self);
}


static void daemon_irc_irc_connection_Connected (DaemonIRCIRCConnection* self) {
	const gchar* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
	daemon_global_log_ColorMessage (DAEMON_CONSOLE_COLORS_Green, "Successfully connected to Server: %s", _tmp0_);
	daemon_irc_irc_connection_SendNickname (self);
	daemon_irc_irc_connection_Auth (self);
}


static void daemon_irc_irc_connection_Disconnected (DaemonIRCIRCConnection* self) {
	GSocket* _tmp0_ = NULL;
	GSocket* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_socket_connection_get_socket (self->priv->_socket);
	g_socket_shutdown (_tmp0_, TRUE, TRUE, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch12_g_error;
	}
	goto __finally12;
	__catch12_g_error:
	{
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
	}
	__finally12:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp1_ = g_socket_connection_get_socket (self->priv->_socket);
	g_object_run_dispose ((GObject*) _tmp1_);
	g_io_stream_close ((GIOStream*) self->priv->_socket, NULL, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch13_g_error;
	}
	goto __finally13;
	__catch13_g_error:
	{
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
	}
	__finally13:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	g_object_run_dispose ((GObject*) self->priv->_socket);
	g_object_run_dispose ((GObject*) self->priv->_connection);
	_tmp2_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
	daemon_global_log_Warning ("Disconnected from Server: %s", _tmp2_);
	daemon_irc_irc_connection_Reconnect (self, 0);
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	guint8* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = -1;
	_tmp0_ = strlen (self);
	res_length1 = (gint) _tmp0_;
	_tmp1_ = res;
	*result_length1 = res_length1;
	result = _tmp1_;
	return result;
}


static void daemon_irc_irc_connection_SendCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* prepared;
	GOutputStream* _tmp4_ = NULL;
	guint8* _tmp5_ = NULL;
	gint _tmp6_;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (command != NULL);
	_tmp0_ = daemon_irc_command_Prepare (command);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat (_tmp1_, "\r\n", NULL);
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	prepared = _tmp3_;
	_tmp4_ = g_io_stream_get_output_stream ((GIOStream*) self->priv->_socket);
	_tmp5_ = string_get_data (prepared, &_tmp6_);
	g_output_stream_write (_tmp4_, _tmp5_, (gsize) _tmp6_, NULL, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch14_g_error;
	}
	goto __finally14;
	__catch14_g_error:
	{
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
		daemon_irc_irc_connection_Disconnected (self);
		_g_free0 (prepared);
		return;
	}
	__finally14:
	if (_inner_error_ != NULL) {
		_g_free0 (prepared);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp7_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
	_tmp8_ = daemon_irc_command_ToString (command);
	_tmp9_ = _tmp8_;
	daemon_global_log_ColorMessage (DAEMON_CONSOLE_COLORS_Yellow, "@%s Sent\n%s", _tmp7_, _tmp9_);
	_g_free0 (_tmp9_);
	_g_free0 (prepared);
}


static void daemon_irc_irc_connection_QueueCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command) {
	DaemonIRCCommand* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (command != NULL);
	_tmp0_ = _g_object_ref0 (command);
	self->priv->_waitingCommands = g_list_append (self->priv->_waitingCommands, _tmp0_);
}


static void daemon_irc_irc_connection_Receive (DaemonIRCIRCConnection* self, GIOChannel* source) {
	gchar* receivedText = NULL;
	GIOStatus status = 0;
	gchar* _tmp0_ = NULL;
	GIOStatus _tmp1_;
	GIOStatus _tmp2_;
	gboolean _tmp3_ = FALSE;
	DaemonIRCCommand* receivedCommand;
	DaemonIRCCommand* _tmp4_ = NULL;
	DaemonIRCCommand* _tmp5_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	_tmp1_ = g_io_channel_read_line (source, &_tmp0_, NULL, NULL, &_inner_error_);
	_g_free0 (receivedText);
	receivedText = _tmp0_;
	_tmp2_ = _tmp1_;
	if (_inner_error_ != NULL) {
		goto __catch15_g_error;
	}
	status = _tmp2_;
	goto __finally15;
	__catch15_g_error:
	{
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
		status = G_IO_STATUS_ERROR;
	}
	__finally15:
	if (_inner_error_ != NULL) {
		_g_free0 (receivedText);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	if (status == G_IO_STATUS_EOF) {
		_tmp3_ = TRUE;
	} else {
		_tmp3_ = status == G_IO_STATUS_ERROR;
	}
	if (_tmp3_) {
		daemon_irc_irc_connection_Disconnected (self);
		_g_free0 (receivedText);
		return;
	}
	receivedCommand = NULL;
	_tmp4_ = daemon_irc_command_Parse (receivedText, &_inner_error_);
	_tmp5_ = _tmp4_;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == DAEMON_IRC_COMMAND_ERROR) {
			goto __catch16_daemon_irc_command_error;
		}
		_g_object_unref0 (receivedCommand);
		_g_free0 (receivedText);
		g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (receivedCommand);
	receivedCommand = _tmp5_;
	goto __finally16;
	__catch16_daemon_irc_command_error:
	{
		GError * _error_;
		const gchar* _tmp6_ = NULL;
		_error_ = _inner_error_;
		_inner_error_ = NULL;
		_tmp6_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
		daemon_global_log_Warning ("@%s - Could not understand command '%s", _tmp6_, receivedText);
		_g_error_free0 (_error_);
		_g_object_unref0 (receivedCommand);
		_g_free0 (receivedText);
		return;
	}
	__finally16:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (receivedCommand);
		_g_free0 (receivedText);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	if (receivedCommand != NULL) {
		daemon_irc_irc_connection_ReceivedCommand (self, receivedCommand);
	}
	_g_object_unref0 (receivedCommand);
	_g_free0 (receivedText);
}


gboolean daemon_irc_irc_connection_InputWatch (DaemonIRCIRCConnection* self, GIOChannel* source, GIOCondition condition) {
	gboolean result = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp6_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (source != NULL, FALSE);
	if ((condition & G_IO_ERR) == G_IO_ERR) {
		const gchar* _tmp0_ = NULL;
		gboolean _tmp1_;
		_tmp0_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
		daemon_global_log_Error ("@%s - Connection Error", _tmp0_);
		_tmp1_ = g_io_stream_is_closed ((GIOStream*) self->priv->_socket);
		if (_tmp1_) {
			daemon_irc_irc_connection_Disconnected (self);
		}
		result = TRUE;
		return result;
	}
	if ((condition & G_IO_NVAL) == G_IO_NVAL) {
		_tmp2_ = TRUE;
	} else {
		_tmp2_ = (condition & G_IO_HUP) == G_IO_HUP;
	}
	if (_tmp2_) {
		daemon_irc_irc_connection_Disconnected (self);
		result = TRUE;
		return result;
	}
	if ((condition & G_IO_OUT) == G_IO_OUT) {
		guint _tmp3_;
		_tmp3_ = g_list_length (self->priv->_waitingCommands);
		if (_tmp3_ > 0) {
			gconstpointer _tmp4_ = NULL;
			DaemonIRCCommand* _tmp5_;
			DaemonIRCCommand* commandToSend;
			_tmp4_ = g_list_nth_data (self->priv->_waitingCommands, (guint) 0);
			_tmp5_ = _g_object_ref0 ((DaemonIRCCommand*) _tmp4_);
			commandToSend = _tmp5_;
			self->priv->_waitingCommands = g_list_remove (self->priv->_waitingCommands, commandToSend);
			daemon_irc_irc_connection_SendCommand (self, commandToSend);
			_g_object_unref0 (commandToSend);
		}
	}
	if ((condition & G_IO_PRI) == G_IO_PRI) {
		_tmp6_ = TRUE;
	} else {
		_tmp6_ = (condition & G_IO_IN) == G_IO_IN;
	}
	if (_tmp6_) {
		daemon_irc_irc_connection_Receive (self, source);
	}
	result = TRUE;
	return result;
}


static void daemon_irc_irc_connection_SendNickname (DaemonIRCIRCConnection* self) {
	gchar** _tmp0_ = NULL;
	gint _tmp1_;
	gchar** _tmp3_ = NULL;
	gint _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar** _tmp7_ = NULL;
	gchar** _tmp8_;
	gint _tmp8__length1;
	DaemonIRCCommand* _tmp9_ = NULL;
	DaemonIRCCommand* _tmp10_;
	g_return_if_fail (self != NULL);
	_tmp0_ = daemon_irc_irc_connection_get_Nicknames (&_tmp1_);
	if (self->priv->_nickIndex >= _tmp1_) {
		gchar* _tmp2_;
		self->priv->_nickIndex = 0;
		_tmp2_ = g_strconcat (self->priv->_nickSuffix, "_", NULL);
		_g_free0 (self->priv->_nickSuffix);
		self->priv->_nickSuffix = _tmp2_;
	}
	_tmp3_ = daemon_irc_irc_connection_get_Nicknames (&_tmp4_);
	_tmp5_ = g_strconcat (_tmp3_[self->priv->_nickIndex], self->priv->_nickSuffix, NULL);
	_g_free0 (self->priv->_lastNick);
	self->priv->_lastNick = _tmp5_;
	_tmp6_ = g_strdup (self->priv->_lastNick);
	_tmp7_ = g_new0 (gchar*, 1 + 1);
	_tmp7_[0] = _tmp6_;
	_tmp8_ = _tmp7_;
	_tmp8__length1 = 1;
	_tmp9_ = daemon_irc_command_new (DAEMON_IRC_COMMAND_TYPES_Nick, _tmp8_, 1);
	_tmp10_ = _tmp9_;
	daemon_irc_irc_connection_QueueCommand (self, _tmp10_);
	_g_object_unref0 (_tmp10_);
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
	self->priv->_nickIndex++;
}


static void daemon_irc_irc_connection_Auth (DaemonIRCIRCConnection* self) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	gchar** _tmp8_ = NULL;
	gchar** _tmp9_;
	gint _tmp9__length1;
	DaemonIRCCommand* _tmp10_ = NULL;
	DaemonIRCCommand* _tmp11_;
	g_return_if_fail (self != NULL);
	_tmp0_ = daemon_irc_irc_connection_get_Username ();
	_tmp1_ = g_strdup (_tmp0_);
	_tmp2_ = daemon_irc_irc_connection_get_Hostname ();
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = daemon_configuration_server_configuration_get_Host (self->priv->_ServerConfiguration);
	_tmp5_ = g_strdup (_tmp4_);
	_tmp6_ = daemon_irc_irc_connection_get_RealName ();
	_tmp7_ = g_strdup (_tmp6_);
	_tmp8_ = g_new0 (gchar*, 4 + 1);
	_tmp8_[0] = _tmp1_;
	_tmp8_[1] = _tmp3_;
	_tmp8_[2] = _tmp5_;
	_tmp8_[3] = _tmp7_;
	_tmp9_ = _tmp8_;
	_tmp9__length1 = 4;
	_tmp10_ = daemon_irc_command_new (DAEMON_IRC_COMMAND_TYPES_User, _tmp9_, 4);
	_tmp11_ = _tmp10_;
	daemon_irc_irc_connection_QueueCommand (self, _tmp11_);
	_g_object_unref0 (_tmp11_);
	_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
}


static void daemon_irc_irc_connection_JoinChannel (DaemonIRCIRCConnection* self, const gchar* name) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar** _tmp2_ = NULL;
	gchar** _tmp3_;
	gint _tmp3__length1;
	DaemonIRCCommand* _tmp4_ = NULL;
	DaemonIRCCommand* _tmp5_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = g_strdup (name);
	self->priv->_pendingChannels = g_list_append (self->priv->_pendingChannels, _tmp0_);
	_tmp1_ = g_strdup (name);
	_tmp2_ = g_new0 (gchar*, 1 + 1);
	_tmp2_[0] = _tmp1_;
	_tmp3_ = _tmp2_;
	_tmp3__length1 = 1;
	_tmp4_ = daemon_irc_command_new (DAEMON_IRC_COMMAND_TYPES_Join, _tmp3_, 1);
	_tmp5_ = _tmp4_;
	daemon_irc_irc_connection_QueueCommand (self, _tmp5_);
	_g_object_unref0 (_tmp5_);
	_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1, (GDestroyNotify) g_free), NULL);
}


static void daemon_irc_irc_connection_SendMessage (DaemonIRCIRCConnection* self, DaemonIRCEntity* target, const gchar* format, ...) {
	va_list _tmp0_;
	va_list _tmp1_;
	va_list _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gchar* message;
	gchar** _tmp5_;
	gchar** _tmp6_ = NULL;
	gchar** messageLines;
	gint messageLines_length1;
	gint _messageLines_size_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (target != NULL);
	g_return_if_fail (format != NULL);
	va_start (_tmp0_, format);
	_tmp1_ = _tmp0_;
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup_vprintf (format, _tmp2_);
	_tmp4_ = _tmp3_;
	va_end (_tmp2_);
	message = _tmp4_;
	_tmp6_ = _tmp5_ = g_strsplit (message, "\n", 0);
	messageLines = _tmp6_;
	messageLines_length1 = _vala_array_length (_tmp5_);
	_messageLines_size_ = _vala_array_length (_tmp5_);
	{
		gchar** current_collection;
		int current_collection_length1;
		int current_it;
		current_collection = messageLines;
		current_collection_length1 = messageLines_length1;
		for (current_it = 0; current_it < messageLines_length1; current_it = current_it + 1) {
			gchar* _tmp7_;
			gchar* current;
			_tmp7_ = g_strdup (current_collection[current_it]);
			current = _tmp7_;
			{
				const gchar* _tmp8_ = NULL;
				gchar* _tmp9_;
				gchar* _tmp10_;
				gchar** _tmp11_ = NULL;
				gchar** _tmp12_;
				gint _tmp12__length1;
				DaemonIRCCommand* _tmp13_ = NULL;
				DaemonIRCCommand* _tmp14_;
				_tmp8_ = daemon_irc_entity_get_Name (target);
				_tmp9_ = g_strdup (_tmp8_);
				_tmp10_ = g_strdup (current);
				_tmp11_ = g_new0 (gchar*, 2 + 1);
				_tmp11_[0] = _tmp9_;
				_tmp11_[1] = _tmp10_;
				_tmp12_ = _tmp11_;
				_tmp12__length1 = 2;
				_tmp13_ = daemon_irc_command_new (DAEMON_IRC_COMMAND_TYPES_PrivMsg, _tmp12_, 2);
				_tmp14_ = _tmp13_;
				daemon_irc_irc_connection_QueueCommand (self, _tmp14_);
				_g_object_unref0 (_tmp14_);
				_tmp12_ = (_vala_array_free (_tmp12_, _tmp12__length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (current);
			}
		}
	}
	messageLines = (_vala_array_free (messageLines, messageLines_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (message);
}


static void daemon_irc_irc_connection_ReceivedCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command) {
	DaemonConsoleColors _tmp0_ = 0;
	DaemonIRCCodes _tmp1_;
	DaemonConsoleColors color;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gboolean _tmp5_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (command != NULL);
	_tmp1_ = daemon_irc_command_get_Code (command);
	if (_tmp1_ != DAEMON_IRC_CODES_Invalid) {
		_tmp0_ = DAEMON_CONSOLE_COLORS_Purple;
	} else {
		_tmp0_ = DAEMON_CONSOLE_COLORS_Blue;
	}
	color = _tmp0_;
	_tmp2_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
	_tmp3_ = daemon_irc_command_ToString (command);
	_tmp4_ = _tmp3_;
	daemon_global_log_ColorMessage (color, "@%s Received\n%s", _tmp2_, _tmp4_);
	_g_free0 (_tmp4_);
	daemon_irc_irc_connection_ProcessCommand (self, command);
	daemon_irc_irc_connection_ProcessCode (self, command);
	if (self->priv->_authComplete) {
		_tmp5_ = self->priv->_currentNick != NULL;
	} else {
		_tmp5_ = FALSE;
	}
	if (_tmp5_) {
		gchar** _tmp6_ = NULL;
		gint _tmp7_;
		_tmp6_ = daemon_configuration_server_configuration_get_Channels (self->priv->_ServerConfiguration, &_tmp7_);
		{
			gchar** channel_collection;
			int channel_collection_length1;
			int channel_it;
			channel_collection = _tmp6_;
			channel_collection_length1 = _tmp7_;
			for (channel_it = 0; channel_it < _tmp7_; channel_it = channel_it + 1) {
				gchar* _tmp8_;
				gchar* channel;
				_tmp8_ = g_strdup (channel_collection[channel_it]);
				channel = _tmp8_;
				{
					gboolean _tmp9_ = FALSE;
					gboolean _tmp10_;
					_tmp10_ = daemon_irc_irc_connection_InChannel (self, channel);
					if (!_tmp10_) {
						gboolean _tmp11_;
						_tmp11_ = daemon_irc_irc_connection_IsChannelPending (self, channel);
						_tmp9_ = !_tmp11_;
					} else {
						_tmp9_ = FALSE;
					}
					if (_tmp9_) {
						daemon_irc_irc_connection_JoinChannel (self, channel);
					}
					_g_free0 (channel);
				}
			}
		}
	}
}


static gboolean daemon_irc_irc_connection_InChannel (DaemonIRCIRCConnection* self, const gchar* name) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (name != NULL, FALSE);
	{
		GList* current_collection;
		GList* current_it;
		current_collection = self->priv->_channels;
		for (current_it = current_collection; current_it != NULL; current_it = current_it->next) {
			gchar* _tmp0_;
			gchar* current;
			_tmp0_ = g_strdup ((const gchar*) current_it->data);
			current = _tmp0_;
			{
				if (g_strcmp0 (current, name) == 0) {
					result = TRUE;
					_g_free0 (current);
					return result;
				}
				_g_free0 (current);
			}
		}
	}
	result = FALSE;
	return result;
}


static gboolean daemon_irc_irc_connection_IsChannelPending (DaemonIRCIRCConnection* self, const gchar* name) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (name != NULL, FALSE);
	{
		GList* current_collection;
		GList* current_it;
		current_collection = self->priv->_pendingChannels;
		for (current_it = current_collection; current_it != NULL; current_it = current_it->next) {
			gchar* _tmp0_;
			gchar* current;
			_tmp0_ = g_strdup ((const gchar*) current_it->data);
			current = _tmp0_;
			{
				if (g_strcmp0 (current, name) == 0) {
					result = TRUE;
					_g_free0 (current);
					return result;
				}
				_g_free0 (current);
			}
		}
	}
	result = FALSE;
	return result;
}


static void daemon_irc_irc_connection_ProcessCommand (DaemonIRCIRCConnection* self, DaemonIRCCommand* command) {
	DaemonIRCCommandTypes _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (command != NULL);
	_tmp0_ = daemon_irc_command_get_Type (command);
	switch (_tmp0_) {
		case DAEMON_IRC_COMMAND_TYPES_Ping:
		{
			{
				gchar** _tmp1_ = NULL;
				gchar** _tmp2_;
				gint _tmp2__length1;
				DaemonIRCCommand* _tmp3_ = NULL;
				DaemonIRCCommand* _tmp4_;
				_tmp1_ = g_new0 (gchar*, 0 + 1);
				_tmp2_ = _tmp1_;
				_tmp2__length1 = 0;
				_tmp3_ = daemon_irc_command_new (DAEMON_IRC_COMMAND_TYPES_Pong, _tmp2_, 0);
				_tmp4_ = _tmp3_;
				daemon_irc_irc_connection_QueueCommand (self, _tmp4_);
				_g_object_unref0 (_tmp4_);
				_tmp2_ = (_vala_array_free (_tmp2_, _tmp2__length1, (GDestroyNotify) g_free), NULL);
				break;
			}
		}
		case DAEMON_IRC_COMMAND_TYPES_PrivMsg:
		{
			{
				DaemonIRCEntity** _tmp5_ = NULL;
				gint _tmp6_;
				_tmp5_ = daemon_irc_command_get_Receivers (command, &_tmp6_);
				{
					DaemonIRCEntity** receiver_collection;
					int receiver_collection_length1;
					int receiver_it;
					receiver_collection = _tmp5_;
					receiver_collection_length1 = _tmp6_;
					for (receiver_it = 0; receiver_it < _tmp6_; receiver_it = receiver_it + 1) {
						DaemonIRCEntity* _tmp7_;
						DaemonIRCEntity* receiver;
						_tmp7_ = _g_object_ref0 (receiver_collection[receiver_it]);
						receiver = _tmp7_;
						{
							const gchar* _tmp8_ = NULL;
							_tmp8_ = daemon_irc_entity_get_Name (receiver);
							if (g_strcmp0 (_tmp8_, self->priv->_currentNick) == 0) {
								DaemonIRCEntity* _tmp9_ = NULL;
								gchar** _tmp10_ = NULL;
								gint _tmp11_;
								_tmp9_ = daemon_irc_command_get_Sender (command);
								_tmp10_ = daemon_irc_command_get_Parameters (command, &_tmp11_);
								daemon_irc_irc_connection_ProcessMessage (self, _tmp9_, _tmp10_[1]);
							} else {
								const gchar* _tmp12_ = NULL;
								gboolean _tmp13_;
								_tmp12_ = daemon_irc_entity_get_Name (receiver);
								_tmp13_ = daemon_irc_irc_connection_InChannel (self, _tmp12_);
								if (_tmp13_) {
									DaemonIRCEntity* _tmp14_ = NULL;
									const gchar* _tmp15_ = NULL;
									gchar** _tmp16_ = NULL;
									gint _tmp17_;
									const gchar* _tmp18_ = NULL;
									const gchar* _tmp19_ = NULL;
									DaemonEventsMessageEvent* _tmp20_ = NULL;
									DaemonEventsMessageEvent* _tmp21_;
									_tmp14_ = daemon_irc_command_get_Sender (command);
									_tmp15_ = daemon_irc_entity_get_Name (_tmp14_);
									_tmp16_ = daemon_irc_command_get_Parameters (command, &_tmp17_);
									_tmp18_ = daemon_irc_entity_get_Name (receiver);
									_tmp19_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
									_tmp20_ = daemon_events_message_event_new (_tmp15_, _tmp16_[1], _tmp18_, _tmp19_);
									_tmp21_ = _tmp20_;
									daemon_data_irc_log_Log ((DaemonEventsLogEvent*) _tmp21_, &_inner_error_);
									_g_object_unref0 (_tmp21_);
									if (_inner_error_ != NULL) {
										if (_inner_error_->domain == DAEMON_DATA_DATA_ACCESS_ERROR) {
											goto __catch17_daemon_data_data_access_error;
										}
										_g_object_unref0 (receiver);
										g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
										g_clear_error (&_inner_error_);
										return;
									}
									goto __finally17;
									__catch17_daemon_data_data_access_error:
									{
										GError * _error_;
										_error_ = _inner_error_;
										_inner_error_ = NULL;
										daemon_global_log_Error ("%s", _error_->message);
										_g_error_free0 (_error_);
										_g_object_unref0 (receiver);
										break;
									}
									__finally17:
									if (_inner_error_ != NULL) {
										_g_object_unref0 (receiver);
										g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
										g_clear_error (&_inner_error_);
										return;
									}
								}
							}
							_g_object_unref0 (receiver);
						}
					}
				}
				break;
			}
		}
		case DAEMON_IRC_COMMAND_TYPES_Nick:
		{
			{
				DaemonIRCEntity* _tmp22_ = NULL;
				const gchar* _tmp23_ = NULL;
				_tmp22_ = daemon_irc_command_get_Sender (command);
				_tmp23_ = daemon_irc_entity_get_Name (_tmp22_);
				if (g_strcmp0 (_tmp23_, self->priv->_currentNick) == 0) {
					break;
				} else {
					DaemonIRCEntity* _tmp24_ = NULL;
					const gchar* _tmp25_ = NULL;
					DaemonIRCEntity* _tmp26_ = NULL;
					const gchar* _tmp27_ = NULL;
					const gchar* _tmp28_ = NULL;
					DaemonEventsChangeNameEvent* _tmp29_ = NULL;
					DaemonEventsChangeNameEvent* _tmp30_;
					_tmp24_ = daemon_irc_command_get_Sender (command);
					_tmp25_ = daemon_irc_entity_get_Name (_tmp24_);
					_tmp26_ = daemon_irc_command_get_Receiver (command);
					_tmp27_ = daemon_irc_entity_get_Name (_tmp26_);
					_tmp28_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
					_tmp29_ = daemon_events_change_name_event_new (_tmp25_, _tmp27_, "!global", _tmp28_);
					_tmp30_ = _tmp29_;
					daemon_data_irc_log_Log ((DaemonEventsLogEvent*) _tmp30_, &_inner_error_);
					_g_object_unref0 (_tmp30_);
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == DAEMON_DATA_DATA_ACCESS_ERROR) {
							goto __catch18_daemon_data_data_access_error;
						}
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					goto __finally18;
					__catch18_daemon_data_data_access_error:
					{
						GError * _error_;
						_error_ = _inner_error_;
						_inner_error_ = NULL;
						daemon_global_log_Error ("%s", _error_->message);
						_g_error_free0 (_error_);
						break;
					}
					__finally18:
					if (_inner_error_ != NULL) {
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				break;
			}
		}
		case DAEMON_IRC_COMMAND_TYPES_Join:
		{
			{
				DaemonIRCEntity* _tmp31_ = NULL;
				const gchar* _tmp32_ = NULL;
				_tmp31_ = daemon_irc_command_get_Sender (command);
				_tmp32_ = daemon_irc_entity_get_Name (_tmp31_);
				if (g_strcmp0 (_tmp32_, self->priv->_currentNick) == 0) {
					gchar** _tmp33_ = NULL;
					gint _tmp34_;
					gchar* _tmp35_;
					gchar** _tmp36_ = NULL;
					gint _tmp37_;
					_tmp33_ = daemon_irc_command_get_Parameters (command, &_tmp34_);
					_tmp35_ = g_strdup (_tmp33_[0]);
					self->priv->_channels = g_list_append (self->priv->_channels, _tmp35_);
					_tmp36_ = daemon_irc_command_get_Parameters (command, &_tmp37_);
					self->priv->_pendingChannels = g_list_remove (self->priv->_pendingChannels, _tmp36_[0]);
				} else {
					DaemonIRCEntity* _tmp38_ = NULL;
					const gchar* _tmp39_ = NULL;
					gchar** _tmp40_ = NULL;
					gint _tmp41_;
					const gchar* _tmp42_ = NULL;
					DaemonEventsStatusEvent* _tmp43_ = NULL;
					DaemonEventsStatusEvent* _tmp44_;
					_tmp38_ = daemon_irc_command_get_Sender (command);
					_tmp39_ = daemon_irc_entity_get_Name (_tmp38_);
					_tmp40_ = daemon_irc_command_get_Parameters (command, &_tmp41_);
					_tmp42_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
					_tmp43_ = daemon_events_status_event_new (_tmp39_, DAEMON_EVENTS_STATUS_CHANGE_Join, _tmp40_[0], _tmp42_);
					_tmp44_ = _tmp43_;
					daemon_data_irc_log_Log ((DaemonEventsLogEvent*) _tmp44_, &_inner_error_);
					_g_object_unref0 (_tmp44_);
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == DAEMON_DATA_DATA_ACCESS_ERROR) {
							goto __catch19_daemon_data_data_access_error;
						}
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					goto __finally19;
					__catch19_daemon_data_data_access_error:
					{
						GError * _error_;
						_error_ = _inner_error_;
						_inner_error_ = NULL;
						daemon_global_log_Error ("%s", _error_->message);
						_g_error_free0 (_error_);
						break;
					}
					__finally19:
					if (_inner_error_ != NULL) {
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				break;
			}
		}
		case DAEMON_IRC_COMMAND_TYPES_Part:
		{
			{
				DaemonIRCEntity* _tmp45_ = NULL;
				const gchar* _tmp46_ = NULL;
				_tmp45_ = daemon_irc_command_get_Sender (command);
				_tmp46_ = daemon_irc_entity_get_Name (_tmp45_);
				if (g_strcmp0 (_tmp46_, self->priv->_currentNick) == 0) {
					gchar** _tmp47_ = NULL;
					gint _tmp48_;
					_tmp47_ = daemon_irc_command_get_Parameters (command, &_tmp48_);
					self->priv->_channels = g_list_remove (self->priv->_channels, _tmp47_[0]);
				} else {
					DaemonIRCEntity* _tmp49_ = NULL;
					const gchar* _tmp50_ = NULL;
					gchar** _tmp51_ = NULL;
					gint _tmp52_;
					const gchar* _tmp53_ = NULL;
					DaemonEventsStatusEvent* _tmp54_ = NULL;
					DaemonEventsStatusEvent* _tmp55_;
					_tmp49_ = daemon_irc_command_get_Sender (command);
					_tmp50_ = daemon_irc_entity_get_Name (_tmp49_);
					_tmp51_ = daemon_irc_command_get_Parameters (command, &_tmp52_);
					_tmp53_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
					_tmp54_ = daemon_events_status_event_new (_tmp50_, DAEMON_EVENTS_STATUS_CHANGE_Leave, _tmp51_[1], _tmp53_);
					_tmp55_ = _tmp54_;
					daemon_data_irc_log_Log ((DaemonEventsLogEvent*) _tmp55_, &_inner_error_);
					_g_object_unref0 (_tmp55_);
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == DAEMON_DATA_DATA_ACCESS_ERROR) {
							goto __catch20_daemon_data_data_access_error;
						}
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					goto __finally20;
					__catch20_daemon_data_data_access_error:
					{
						GError * _error_;
						_error_ = _inner_error_;
						_inner_error_ = NULL;
						daemon_global_log_Error ("%s", _error_->message);
						_g_error_free0 (_error_);
						break;
					}
					__finally20:
					if (_inner_error_ != NULL) {
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				break;
			}
		}
		default:
		break;
	}
}


static void daemon_irc_irc_connection_ProcessCode (DaemonIRCIRCConnection* self, DaemonIRCCommand* command) {
	DaemonIRCCodes _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (command != NULL);
	_tmp0_ = daemon_irc_command_get_Code (command);
	switch (_tmp0_) {
		case DAEMON_IRC_CODES_NicknameInUse:
		case DAEMON_IRC_CODES_NickCollision:
		{
			{
				daemon_irc_irc_connection_SendNickname (self);
				return;
			}
		}
		case DAEMON_IRC_CODES_LUserClient:
		{
			{
				gchar** _tmp1_ = NULL;
				gint _tmp2_;
				gchar* _tmp3_;
				_tmp1_ = daemon_irc_command_get_Parameters (command, &_tmp2_);
				_tmp3_ = g_strdup (_tmp1_[0]);
				_g_free0 (self->priv->_currentNick);
				self->priv->_currentNick = _tmp3_;
				self->priv->_authComplete = TRUE;
				break;
			}
		}
		default:
		break;
	}
}


static void daemon_irc_irc_connection_SendUnavailable (DaemonIRCIRCConnection* self, DaemonIRCEntity* receiver) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (receiver != NULL);
	daemon_irc_irc_connection_SendMessage (self, receiver, "Currently unavailable, try again in a few minutes");
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _result_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	g_strstrip (_result_);
	result = _result_;
	return result;
}


static void daemon_irc_irc_connection_ProcessMessage (DaemonIRCIRCConnection* self, DaemonIRCEntity* sender, const gchar* message) {
	gchar** _tmp0_;
	gchar** _tmp1_ = NULL;
	gchar** parts;
	gint parts_length1;
	gint _parts_size_;
	const gchar* _tmp2_;
	GQuark _tmp3_;
	static GQuark _tmp3__label0 = 0;
	static GQuark _tmp3__label1 = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	g_return_if_fail (message != NULL);
	_tmp1_ = _tmp0_ = g_strsplit (message, " ", 0);
	parts = _tmp1_;
	parts_length1 = _vala_array_length (_tmp0_);
	_parts_size_ = _vala_array_length (_tmp0_);
	_tmp2_ = parts[0];
	_tmp3_ = (NULL == _tmp2_) ? 0 : g_quark_from_string (_tmp2_);
	if (_tmp3_ == ((0 != _tmp3__label0) ? _tmp3__label0 : (_tmp3__label0 = g_quark_from_static_string ("LASTSEEN")))) {
		switch (0) {
			default:
			{
				{
					gchar* _tmp4_;
					gchar* otherUser;
					gchar* _tmp5_;
					gchar* channel;
					gboolean _tmp6_ = FALSE;
					gboolean _tmp7_ = FALSE;
					GDateTime* lastSeen = NULL;
					DaemonDataIDataAccess* _tmp12_ = NULL;
					const gchar* _tmp13_ = NULL;
					GDateTime* _tmp14_ = NULL;
					GDateTime* _tmp15_;
					gchar* _tmp16_ = NULL;
					gchar* _tmp17_;
					_tmp4_ = g_strdup ("");
					otherUser = _tmp4_;
					_tmp5_ = g_strdup ("");
					channel = _tmp5_;
					if (parts_length1 != 3) {
						_tmp7_ = TRUE;
					} else {
						gchar* _tmp8_ = NULL;
						gint _tmp9_;
						_tmp8_ = string_strip (parts[1]);
						_g_free0 (channel);
						channel = _tmp8_;
						_tmp9_ = strlen (channel);
						_tmp7_ = _tmp9_ == 0;
					}
					if (_tmp7_) {
						_tmp6_ = TRUE;
					} else {
						gchar* _tmp10_ = NULL;
						gint _tmp11_;
						_tmp10_ = string_strip (parts[2]);
						_g_free0 (otherUser);
						otherUser = _tmp10_;
						_tmp11_ = strlen (otherUser);
						_tmp6_ = _tmp11_ == 0;
					}
					if (_tmp6_) {
						daemon_irc_irc_connection_SendMessage (self, sender, "LASTSEEN requires exactly two parameter: The Channels and the Users na" \
"me");
						_g_free0 (channel);
						_g_free0 (otherUser);
						break;
					}
					_tmp12_ = daemon_plugin_manager_get_DataAccess ();
					_tmp13_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
					_tmp14_ = daemon_data_idata_access_UserLastSeen (_tmp12_, otherUser, channel, _tmp13_, &_inner_error_);
					_tmp15_ = _tmp14_;
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == DAEMON_DATA_DATA_ACCESS_ERROR) {
							goto __catch21_daemon_data_data_access_error;
						}
						_g_date_time_unref0 (lastSeen);
						_g_free0 (channel);
						_g_free0 (otherUser);
						parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					_g_date_time_unref0 (lastSeen);
					lastSeen = _tmp15_;
					goto __finally21;
					__catch21_daemon_data_data_access_error:
					{
						GError * _error_;
						_error_ = _inner_error_;
						_inner_error_ = NULL;
						daemon_irc_irc_connection_SendUnavailable (self, sender);
						_g_error_free0 (_error_);
						_g_date_time_unref0 (lastSeen);
						_g_free0 (channel);
						_g_free0 (otherUser);
						break;
					}
					__finally21:
					if (_inner_error_ != NULL) {
						_g_date_time_unref0 (lastSeen);
						_g_free0 (channel);
						_g_free0 (otherUser);
						parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					if (lastSeen == NULL) {
						daemon_irc_irc_connection_SendMessage (self, sender, "I have never seen User %s on Channel %s", otherUser, channel);
						_g_date_time_unref0 (lastSeen);
						_g_free0 (channel);
						_g_free0 (otherUser);
						break;
					}
					_tmp16_ = g_date_time_format (lastSeen, "%x %X");
					_tmp17_ = _tmp16_;
					daemon_irc_irc_connection_SendMessage (self, sender, "The last time user %s did something on Channel %s was at %s", otherUser, channel, _tmp17_);
					_g_free0 (_tmp17_);
					_g_date_time_unref0 (lastSeen);
					_g_free0 (channel);
					_g_free0 (otherUser);
					break;
				}
			}
		}
	} else if (_tmp3_ == ((0 != _tmp3__label1) ? _tmp3__label1 : (_tmp3__label1 = g_quark_from_static_string ("SENDLOG")))) {
		switch (0) {
			default:
			{
				{
					gchar* _tmp18_;
					gchar* channel;
					gchar* _tmp19_;
					gchar* email;
					gboolean _tmp20_ = FALSE;
					gboolean _tmp21_ = FALSE;
					GList* log;
					DaemonDataIDataAccess* _tmp26_ = NULL;
					const gchar* _tmp27_ = NULL;
					GList* _tmp28_ = NULL;
					GList* _tmp29_;
					GString* _tmp30_ = NULL;
					GString* builder;
					const gchar* _tmp31_ = NULL;
					gchar* _tmp32_ = NULL;
					gchar* _tmp33_;
					DaemonEmailSender* _tmp37_ = NULL;
					DaemonEmailSender* emailSender;
					gchar* _tmp38_ = NULL;
					gchar* _tmp39_;
					_tmp18_ = g_strdup ("");
					channel = _tmp18_;
					_tmp19_ = g_strdup ("");
					email = _tmp19_;
					if (parts_length1 != 3) {
						_tmp21_ = TRUE;
					} else {
						gchar* _tmp22_ = NULL;
						gint _tmp23_;
						_tmp22_ = string_strip (parts[1]);
						_g_free0 (channel);
						channel = _tmp22_;
						_tmp23_ = strlen (channel);
						_tmp21_ = _tmp23_ == 0;
					}
					if (_tmp21_) {
						_tmp20_ = TRUE;
					} else {
						gchar* _tmp24_ = NULL;
						gint _tmp25_;
						_tmp24_ = string_strip (parts[2]);
						_g_free0 (email);
						email = _tmp24_;
						_tmp25_ = strlen (email);
						_tmp20_ = _tmp25_ == 0;
					}
					if (_tmp20_) {
						daemon_irc_irc_connection_SendMessage (self, sender, "SENDLOG requires exactly two parameter: The Channels name and a E-Mail" \
" address");
						_g_free0 (email);
						_g_free0 (channel);
						break;
					}
					log = NULL;
					_tmp26_ = daemon_plugin_manager_get_DataAccess ();
					_tmp27_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
					_tmp28_ = daemon_data_idata_access_GetLog (_tmp26_, channel, _tmp27_, &_inner_error_);
					_tmp29_ = _tmp28_;
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == DAEMON_DATA_DATA_ACCESS_ERROR) {
							goto __catch22_daemon_data_data_access_error;
						}
						__g_list_free__g_object_unref0_0 (log);
						_g_free0 (email);
						_g_free0 (channel);
						parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					__g_list_free__g_object_unref0_0 (log);
					log = _tmp29_;
					goto __finally22;
					__catch22_daemon_data_data_access_error:
					{
						GError * _error_;
						_error_ = _inner_error_;
						_inner_error_ = NULL;
						daemon_irc_irc_connection_SendUnavailable (self, sender);
						_g_error_free0 (_error_);
					}
					__finally22:
					if (_inner_error_ != NULL) {
						__g_list_free__g_object_unref0_0 (log);
						_g_free0 (email);
						_g_free0 (channel);
						parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					_tmp30_ = g_string_new ("");
					builder = _tmp30_;
					_tmp31_ = daemon_configuration_server_configuration_get_Name (self->priv->_ServerConfiguration);
					_tmp32_ = g_strdup_printf ("Starting log for channel %s on server %s\n\n", channel, _tmp31_);
					_tmp33_ = _tmp32_;
					g_string_append (builder, _tmp33_);
					_g_free0 (_tmp33_);
					{
						GList* current_collection;
						GList* current_it;
						current_collection = log;
						for (current_it = current_collection; current_it != NULL; current_it = current_it->next) {
							DaemonEventsLogEvent* _tmp34_;
							DaemonEventsLogEvent* current;
							_tmp34_ = _g_object_ref0 ((DaemonEventsLogEvent*) current_it->data);
							current = _tmp34_;
							{
								gchar* _tmp35_ = NULL;
								gchar* _tmp36_;
								_tmp35_ = daemon_events_log_event_ToString (current);
								_tmp36_ = _tmp35_;
								g_string_append (builder, _tmp36_);
								_g_free0 (_tmp36_);
								g_string_append (builder, "\n");
								_g_object_unref0 (current);
							}
						}
					}
					g_string_append (builder, "\nEND OF LOG");
					_tmp37_ = daemon_email_sender_new ();
					emailSender = _tmp37_;
					_tmp38_ = g_strdup_printf ("Log for channel %s", channel);
					_tmp39_ = _tmp38_;
					daemon_email_sender_SendEmail (emailSender, email, _tmp39_, builder->str, &_inner_error_);
					_g_free0 (_tmp39_);
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == DAEMON_EMAIL_ERROR) {
							goto __catch23_daemon_email_error;
						}
						_daemon_email_sender_unref0 (emailSender);
						_g_string_free0 (builder);
						__g_list_free__g_object_unref0_0 (log);
						_g_free0 (email);
						_g_free0 (channel);
						parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					goto __finally23;
					__catch23_daemon_email_error:
					{
						GError * _error_;
						_error_ = _inner_error_;
						_inner_error_ = NULL;
						daemon_irc_irc_connection_SendMessage (self, sender, "Could not send E-Mail to %s, might be a wrong address?", email);
						_g_error_free0 (_error_);
						_daemon_email_sender_unref0 (emailSender);
						_g_string_free0 (builder);
						__g_list_free__g_object_unref0_0 (log);
						_g_free0 (email);
						_g_free0 (channel);
						break;
					}
					__finally23:
					if (_inner_error_ != NULL) {
						_daemon_email_sender_unref0 (emailSender);
						_g_string_free0 (builder);
						__g_list_free__g_object_unref0_0 (log);
						_g_free0 (email);
						_g_free0 (channel);
						parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
					daemon_irc_irc_connection_SendMessage (self, sender, "Great success!");
					_daemon_email_sender_unref0 (emailSender);
					_g_string_free0 (builder);
					__g_list_free__g_object_unref0_0 (log);
					_g_free0 (email);
					_g_free0 (channel);
					break;
				}
			}
		}
	} else {
		switch (0) {
			default:
			{
				{
					daemon_irc_irc_connection_NotUnderstood (self, sender);
					break;
				}
			}
		}
	}
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
}


static void daemon_irc_irc_connection_NotUnderstood (DaemonIRCIRCConnection* self, DaemonIRCEntity* sender) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	daemon_irc_irc_connection_SendMessage (self, sender, "%s", DAEMON_IRC_IRC_CONNECTION__helpString);
}


const gchar* daemon_irc_irc_connection_get_RealName (void) {
	const gchar* result;
	result = daemon_irc_irc_connection__RealName;
	return result;
}


void daemon_irc_irc_connection_set_RealName (const gchar* value) {
	gchar* _tmp0_;
	_tmp0_ = g_strdup (value);
	_g_free0 (daemon_irc_irc_connection__RealName);
	daemon_irc_irc_connection__RealName = _tmp0_;
}


gchar** daemon_irc_irc_connection_get_Nicknames (int* result_length1) {
	gchar** result;
	gchar** _tmp0_;
	_tmp0_ = daemon_irc_irc_connection__Nicknames;
	*result_length1 = daemon_irc_irc_connection__Nicknames_length1;
	result = _tmp0_;
	return result;
}


static gchar** _vala_array_dup4 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		result[i] = g_strdup (self[i]);
	}
	return result;
}


void daemon_irc_irc_connection_set_Nicknames (gchar** value, int value_length1) {
	gchar** _tmp0_;
	gchar** _tmp1_;
	_tmp0_ = (_tmp1_ = value, (_tmp1_ == NULL) ? ((gpointer) _tmp1_) : _vala_array_dup4 (_tmp1_, value_length1));
	daemon_irc_irc_connection__Nicknames = (_vala_array_free (daemon_irc_irc_connection__Nicknames, daemon_irc_irc_connection__Nicknames_length1, (GDestroyNotify) g_free), NULL);
	daemon_irc_irc_connection__Nicknames = _tmp0_;
	daemon_irc_irc_connection__Nicknames_length1 = value_length1;
	_daemon_irc_irc_connection__Nicknames_size_ = value_length1;
}


const gchar* daemon_irc_irc_connection_get_Hostname (void) {
	const gchar* result;
	result = daemon_irc_irc_connection__Hostname;
	return result;
}


void daemon_irc_irc_connection_set_Hostname (const gchar* value) {
	gchar* _tmp0_;
	_tmp0_ = g_strdup (value);
	_g_free0 (daemon_irc_irc_connection__Hostname);
	daemon_irc_irc_connection__Hostname = _tmp0_;
}


const gchar* daemon_irc_irc_connection_get_Username (void) {
	const gchar* result;
	result = daemon_irc_irc_connection__Username;
	return result;
}


void daemon_irc_irc_connection_set_Username (const gchar* value) {
	gchar* _tmp0_;
	_tmp0_ = g_strdup (value);
	_g_free0 (daemon_irc_irc_connection__Username);
	daemon_irc_irc_connection__Username = _tmp0_;
}


DaemonConfigurationServerConfiguration* daemon_irc_irc_connection_get_ServerConfiguration (DaemonIRCIRCConnection* self) {
	DaemonConfigurationServerConfiguration* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_ServerConfiguration;
	return result;
}


static void daemon_irc_irc_connection_set_ServerConfiguration (DaemonIRCIRCConnection* self, DaemonConfigurationServerConfiguration* value) {
	DaemonConfigurationServerConfiguration* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _g_object_ref0 (value);
	_g_object_unref0 (self->priv->_ServerConfiguration);
	self->priv->_ServerConfiguration = _tmp0_;
	g_object_notify ((GObject *) self, "ServerConfiguration");
}


const gchar* daemon_irc_irc_connection_get_Host (DaemonIRCIRCConnection* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Host;
	return result;
}


static void daemon_irc_irc_connection_set_Host (DaemonIRCIRCConnection* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Host);
	self->priv->_Host = _tmp0_;
	g_object_notify ((GObject *) self, "Host");
}


guint16 daemon_irc_irc_connection_get_Port (DaemonIRCIRCConnection* self) {
	guint16 result;
	g_return_val_if_fail (self != NULL, 0U);
	result = self->priv->_Port;
	return result;
}


static void daemon_irc_irc_connection_set_Port (DaemonIRCIRCConnection* self, guint16 value) {
	g_return_if_fail (self != NULL);
	self->priv->_Port = value;
}


GInetAddress* daemon_irc_irc_connection_get_Address (DaemonIRCIRCConnection* self) {
	GInetAddress* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Address;
	return result;
}


static void daemon_irc_irc_connection_set_Address (DaemonIRCIRCConnection* self, GInetAddress* value) {
	GInetAddress* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _g_object_ref0 (value);
	_g_object_unref0 (self->priv->_Address);
	self->priv->_Address = _tmp0_;
	g_object_notify ((GObject *) self, "Address");
}


GInetSocketAddress* daemon_irc_irc_connection_get_Endpoint (DaemonIRCIRCConnection* self) {
	GInetSocketAddress* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Endpoint;
	return result;
}


static void daemon_irc_irc_connection_set_Endpoint (DaemonIRCIRCConnection* self, GInetSocketAddress* value) {
	GInetSocketAddress* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _g_object_ref0 (value);
	_g_object_unref0 (self->priv->_Endpoint);
	self->priv->_Endpoint = _tmp0_;
	g_object_notify ((GObject *) self, "Endpoint");
}


static void daemon_irc_irc_connection_class_init (DaemonIRCIRCConnectionClass * klass) {
	daemon_irc_irc_connection_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DaemonIRCIRCConnectionPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_daemon_irc_irc_connection_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_daemon_irc_irc_connection_set_property;
	G_OBJECT_CLASS (klass)->finalize = daemon_irc_irc_connection_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), DAEMON_IRC_IRC_CONNECTION_SERVER_CONFIGURATION, g_param_spec_object ("ServerConfiguration", "ServerConfiguration", "ServerConfiguration", DAEMON_CONFIGURATION_TYPE_SERVER_CONFIGURATION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DAEMON_IRC_IRC_CONNECTION_HOST, g_param_spec_string ("Host", "Host", "Host", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DAEMON_IRC_IRC_CONNECTION_ADDRESS, g_param_spec_object ("Address", "Address", "Address", G_TYPE_INET_ADDRESS, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DAEMON_IRC_IRC_CONNECTION_ENDPOINT, g_param_spec_object ("Endpoint", "Endpoint", "Endpoint", G_TYPE_INET_SOCKET_ADDRESS, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void daemon_irc_irc_connection_instance_init (DaemonIRCIRCConnection * self) {
	gchar* _tmp0_;
	self->priv = DAEMON_IRC_IRC_CONNECTION_GET_PRIVATE (self);
	self->priv->_channels = NULL;
	self->priv->_pendingChannels = NULL;
	self->priv->_waitingCommands = NULL;
	self->priv->_nickIndex = 0;
	_tmp0_ = g_strdup ("");
	self->priv->_nickSuffix = _tmp0_;
	self->priv->_lastNick = NULL;
	self->priv->_currentNick = NULL;
	self->priv->_authComplete = FALSE;
}


static void daemon_irc_irc_connection_finalize (GObject* obj) {
	DaemonIRCIRCConnection * self;
	self = DAEMON_IRC_IRC_CONNECTION (obj);
	_g_object_unref0 (self->priv->_connection);
	_g_object_unref0 (self->priv->_ServerConfiguration);
	_g_free0 (self->priv->_Host);
	_g_object_unref0 (self->priv->_Address);
	_g_object_unref0 (self->priv->_Endpoint);
	_g_object_unref0 (self->priv->_socket);
	_g_object_unref0 (self->priv->_inputStream);
	_g_io_channel_unref0 (self->priv->_channel);
	__g_list_free__g_free0_0 (self->priv->_channels);
	__g_list_free__g_free0_0 (self->priv->_pendingChannels);
	__g_list_free__g_object_unref0_0 (self->priv->_waitingCommands);
	_g_free0 (self->priv->_nickSuffix);
	_g_free0 (self->priv->_lastNick);
	_g_free0 (self->priv->_currentNick);
	G_OBJECT_CLASS (daemon_irc_irc_connection_parent_class)->finalize (obj);
}


GType daemon_irc_irc_connection_get_type (void) {
	static volatile gsize daemon_irc_irc_connection_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_irc_irc_connection_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DaemonIRCIRCConnectionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) daemon_irc_irc_connection_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DaemonIRCIRCConnection), 0, (GInstanceInitFunc) daemon_irc_irc_connection_instance_init, NULL };
		GType daemon_irc_irc_connection_type_id;
		daemon_irc_irc_connection_type_id = g_type_register_static (G_TYPE_OBJECT, "DaemonIRCIRCConnection", &g_define_type_info, 0);
		g_once_init_leave (&daemon_irc_irc_connection_type_id__volatile, daemon_irc_irc_connection_type_id);
	}
	return daemon_irc_irc_connection_type_id__volatile;
}


static void _vala_daemon_irc_irc_connection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DaemonIRCIRCConnection * self;
	self = DAEMON_IRC_IRC_CONNECTION (object);
	switch (property_id) {
		case DAEMON_IRC_IRC_CONNECTION_SERVER_CONFIGURATION:
		g_value_set_object (value, daemon_irc_irc_connection_get_ServerConfiguration (self));
		break;
		case DAEMON_IRC_IRC_CONNECTION_HOST:
		g_value_set_string (value, daemon_irc_irc_connection_get_Host (self));
		break;
		case DAEMON_IRC_IRC_CONNECTION_ADDRESS:
		g_value_set_object (value, daemon_irc_irc_connection_get_Address (self));
		break;
		case DAEMON_IRC_IRC_CONNECTION_ENDPOINT:
		g_value_set_object (value, daemon_irc_irc_connection_get_Endpoint (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_daemon_irc_irc_connection_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DaemonIRCIRCConnection * self;
	self = DAEMON_IRC_IRC_CONNECTION (object);
	switch (property_id) {
		case DAEMON_IRC_IRC_CONNECTION_SERVER_CONFIGURATION:
		daemon_irc_irc_connection_set_ServerConfiguration (self, g_value_get_object (value));
		break;
		case DAEMON_IRC_IRC_CONNECTION_HOST:
		daemon_irc_irc_connection_set_Host (self, g_value_get_string (value));
		break;
		case DAEMON_IRC_IRC_CONNECTION_ADDRESS:
		daemon_irc_irc_connection_set_Address (self, g_value_get_object (value));
		break;
		case DAEMON_IRC_IRC_CONNECTION_ENDPOINT:
		daemon_irc_irc_connection_set_Endpoint (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



