/* DateTimeConverter.c generated by valac 0.12.0, the Vala compiler
 * generated from DateTimeConverter.vala, do not modify */

/*SemesterLeistung - An IRC Daemon
* Copyright (C) 2011  Simon Baumer
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER (daemon_helpers_date_time_converter_get_type ())
#define DAEMON_HELPERS_DATE_TIME_CONVERTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER, DaemonHelpersDateTimeConverter))
#define DAEMON_HELPERS_DATE_TIME_CONVERTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER, DaemonHelpersDateTimeConverterClass))
#define DAEMON_HELPERS_IS_DATE_TIME_CONVERTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER))
#define DAEMON_HELPERS_IS_DATE_TIME_CONVERTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER))
#define DAEMON_HELPERS_DATE_TIME_CONVERTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER, DaemonHelpersDateTimeConverterClass))

typedef struct _DaemonHelpersDateTimeConverter DaemonHelpersDateTimeConverter;
typedef struct _DaemonHelpersDateTimeConverterClass DaemonHelpersDateTimeConverterClass;
typedef struct _DaemonHelpersDateTimeConverterPrivate DaemonHelpersDateTimeConverterPrivate;
typedef struct _DaemonHelpersParamSpecDateTimeConverter DaemonHelpersParamSpecDateTimeConverter;

struct _DaemonHelpersDateTimeConverter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DaemonHelpersDateTimeConverterPrivate * priv;
};

struct _DaemonHelpersDateTimeConverterClass {
	GTypeClass parent_class;
	void (*finalize) (DaemonHelpersDateTimeConverter *self);
};

struct _DaemonHelpersParamSpecDateTimeConverter {
	GParamSpec parent_instance;
};


static gpointer daemon_helpers_date_time_converter_parent_class = NULL;

gpointer daemon_helpers_date_time_converter_ref (gpointer instance);
void daemon_helpers_date_time_converter_unref (gpointer instance);
GParamSpec* daemon_helpers_param_spec_date_time_converter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void daemon_helpers_value_set_date_time_converter (GValue* value, gpointer v_object);
void daemon_helpers_value_take_date_time_converter (GValue* value, gpointer v_object);
gpointer daemon_helpers_value_get_date_time_converter (const GValue* value);
GType daemon_helpers_date_time_converter_get_type (void) G_GNUC_CONST;
enum  {
	DAEMON_HELPERS_DATE_TIME_CONVERTER_DUMMY_PROPERTY
};
gint64 daemon_helpers_date_time_converter_ToUnixTimestamp (GDateTime* dateTime);
GDateTime* daemon_helpers_date_time_converter_FromUnixTimestamp (gint64 timestamp);
DaemonHelpersDateTimeConverter* daemon_helpers_date_time_converter_new (void);
DaemonHelpersDateTimeConverter* daemon_helpers_date_time_converter_construct (GType object_type);
static void daemon_helpers_date_time_converter_finalize (DaemonHelpersDateTimeConverter* obj);


gint64 daemon_helpers_date_time_converter_ToUnixTimestamp (GDateTime* dateTime) {
	gint64 result = 0LL;
	gint64 _tmp0_;
	g_return_val_if_fail (dateTime != NULL, 0LL);
	_tmp0_ = g_date_time_to_unix (dateTime);
	result = _tmp0_;
	return result;
}


GDateTime* daemon_helpers_date_time_converter_FromUnixTimestamp (gint64 timestamp) {
	GDateTime* result = NULL;
	GDateTime* _tmp0_ = NULL;
	_tmp0_ = g_date_time_new_from_unix_local (timestamp);
	result = _tmp0_;
	return result;
}


DaemonHelpersDateTimeConverter* daemon_helpers_date_time_converter_construct (GType object_type) {
	DaemonHelpersDateTimeConverter* self = NULL;
	self = (DaemonHelpersDateTimeConverter*) g_type_create_instance (object_type);
	return self;
}


DaemonHelpersDateTimeConverter* daemon_helpers_date_time_converter_new (void) {
	return daemon_helpers_date_time_converter_construct (DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER);
}


static void daemon_helpers_value_date_time_converter_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void daemon_helpers_value_date_time_converter_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		daemon_helpers_date_time_converter_unref (value->data[0].v_pointer);
	}
}


static void daemon_helpers_value_date_time_converter_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = daemon_helpers_date_time_converter_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer daemon_helpers_value_date_time_converter_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* daemon_helpers_value_date_time_converter_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		DaemonHelpersDateTimeConverter* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = daemon_helpers_date_time_converter_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* daemon_helpers_value_date_time_converter_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	DaemonHelpersDateTimeConverter** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = daemon_helpers_date_time_converter_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* daemon_helpers_param_spec_date_time_converter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	DaemonHelpersParamSpecDateTimeConverter* spec;
	g_return_val_if_fail (g_type_is_a (object_type, DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer daemon_helpers_value_get_date_time_converter (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER), NULL);
	return value->data[0].v_pointer;
}


void daemon_helpers_value_set_date_time_converter (GValue* value, gpointer v_object) {
	DaemonHelpersDateTimeConverter* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		daemon_helpers_date_time_converter_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		daemon_helpers_date_time_converter_unref (old);
	}
}


void daemon_helpers_value_take_date_time_converter (GValue* value, gpointer v_object) {
	DaemonHelpersDateTimeConverter* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DAEMON_HELPERS_TYPE_DATE_TIME_CONVERTER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		daemon_helpers_date_time_converter_unref (old);
	}
}


static void daemon_helpers_date_time_converter_class_init (DaemonHelpersDateTimeConverterClass * klass) {
	daemon_helpers_date_time_converter_parent_class = g_type_class_peek_parent (klass);
	DAEMON_HELPERS_DATE_TIME_CONVERTER_CLASS (klass)->finalize = daemon_helpers_date_time_converter_finalize;
}


static void daemon_helpers_date_time_converter_instance_init (DaemonHelpersDateTimeConverter * self) {
	self->ref_count = 1;
}


static void daemon_helpers_date_time_converter_finalize (DaemonHelpersDateTimeConverter* obj) {
	DaemonHelpersDateTimeConverter * self;
	self = DAEMON_HELPERS_DATE_TIME_CONVERTER (obj);
}


GType daemon_helpers_date_time_converter_get_type (void) {
	static volatile gsize daemon_helpers_date_time_converter_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_helpers_date_time_converter_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { daemon_helpers_value_date_time_converter_init, daemon_helpers_value_date_time_converter_free_value, daemon_helpers_value_date_time_converter_copy_value, daemon_helpers_value_date_time_converter_peek_pointer, "p", daemon_helpers_value_date_time_converter_collect_value, "p", daemon_helpers_value_date_time_converter_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (DaemonHelpersDateTimeConverterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) daemon_helpers_date_time_converter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DaemonHelpersDateTimeConverter), 0, (GInstanceInitFunc) daemon_helpers_date_time_converter_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType daemon_helpers_date_time_converter_type_id;
		daemon_helpers_date_time_converter_type_id = g_type_register_fundamental (g_type_fundamental_next (), "DaemonHelpersDateTimeConverter", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&daemon_helpers_date_time_converter_type_id__volatile, daemon_helpers_date_time_converter_type_id);
	}
	return daemon_helpers_date_time_converter_type_id__volatile;
}


gpointer daemon_helpers_date_time_converter_ref (gpointer instance) {
	DaemonHelpersDateTimeConverter* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void daemon_helpers_date_time_converter_unref (gpointer instance) {
	DaemonHelpersDateTimeConverter* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		DAEMON_HELPERS_DATE_TIME_CONVERTER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



