/* ChangeNameEvent.c generated by valac 0.12.0, the Vala compiler
 * generated from ChangeNameEvent.vala, do not modify */

/*SemesterLeistung - An IRC Daemon
* Copyright (C) 2011  Simon Baumer
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define DAEMON_EVENTS_TYPE_LOG_EVENT (daemon_events_log_event_get_type ())
#define DAEMON_EVENTS_LOG_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEvent))
#define DAEMON_EVENTS_LOG_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEventClass))
#define DAEMON_EVENTS_IS_LOG_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT))
#define DAEMON_EVENTS_IS_LOG_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_EVENTS_TYPE_LOG_EVENT))
#define DAEMON_EVENTS_LOG_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEventClass))

typedef struct _DaemonEventsLogEvent DaemonEventsLogEvent;
typedef struct _DaemonEventsLogEventClass DaemonEventsLogEventClass;
typedef struct _DaemonEventsLogEventPrivate DaemonEventsLogEventPrivate;

#define DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT (daemon_events_change_name_event_get_type ())
#define DAEMON_EVENTS_CHANGE_NAME_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, DaemonEventsChangeNameEvent))
#define DAEMON_EVENTS_CHANGE_NAME_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, DaemonEventsChangeNameEventClass))
#define DAEMON_EVENTS_IS_CHANGE_NAME_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT))
#define DAEMON_EVENTS_IS_CHANGE_NAME_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT))
#define DAEMON_EVENTS_CHANGE_NAME_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, DaemonEventsChangeNameEventClass))

typedef struct _DaemonEventsChangeNameEvent DaemonEventsChangeNameEvent;
typedef struct _DaemonEventsChangeNameEventClass DaemonEventsChangeNameEventClass;
typedef struct _DaemonEventsChangeNameEventPrivate DaemonEventsChangeNameEventPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _DaemonEventsLogEvent {
	GObject parent_instance;
	DaemonEventsLogEventPrivate * priv;
};

struct _DaemonEventsLogEventClass {
	GObjectClass parent_class;
	gchar* (*ToString) (DaemonEventsLogEvent* self);
};

struct _DaemonEventsChangeNameEvent {
	DaemonEventsLogEvent parent_instance;
	DaemonEventsChangeNameEventPrivate * priv;
};

struct _DaemonEventsChangeNameEventClass {
	DaemonEventsLogEventClass parent_class;
};

struct _DaemonEventsChangeNameEventPrivate {
	gchar* _NewUsername;
};


static gpointer daemon_events_change_name_event_parent_class = NULL;

GType daemon_events_log_event_get_type (void) G_GNUC_CONST;
GType daemon_events_change_name_event_get_type (void) G_GNUC_CONST;
#define DAEMON_EVENTS_CHANGE_NAME_EVENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, DaemonEventsChangeNameEventPrivate))
enum  {
	DAEMON_EVENTS_CHANGE_NAME_EVENT_DUMMY_PROPERTY,
	DAEMON_EVENTS_CHANGE_NAME_EVENT_NEW_USERNAME
};
#define DAEMON_EVENTS_CHANGE_NAME_EVENT__stringFormat "%s | User '%s' in Channel '%s' on '%s' changed name to: '%s'"
DaemonEventsChangeNameEvent* daemon_events_change_name_event_new (const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server);
DaemonEventsChangeNameEvent* daemon_events_change_name_event_construct (GType object_type, const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server);
DaemonEventsLogEvent* daemon_events_log_event_construct (GType object_type, const gchar* username, const gchar* channel, const gchar* server);
static void daemon_events_change_name_event_set_NewUsername (DaemonEventsChangeNameEvent* self, const gchar* value);
DaemonEventsChangeNameEvent* daemon_events_change_name_event_new_WithTimestamp (const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server, GDateTime* timestamp);
DaemonEventsChangeNameEvent* daemon_events_change_name_event_construct_WithTimestamp (GType object_type, const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server, GDateTime* timestamp);
DaemonEventsLogEvent* daemon_events_log_event_construct_WithTimestamp (GType object_type, const gchar* username, const gchar* channel, const gchar* server, GDateTime* timestamp);
static gchar* daemon_events_change_name_event_real_ToString (DaemonEventsLogEvent* base);
const gchar* daemon_events_log_event_get_TimestampString (DaemonEventsLogEvent* self);
const gchar* daemon_events_log_event_get_Username (DaemonEventsLogEvent* self);
const gchar* daemon_events_log_event_get_Channel (DaemonEventsLogEvent* self);
const gchar* daemon_events_log_event_get_Server (DaemonEventsLogEvent* self);
const gchar* daemon_events_change_name_event_get_NewUsername (DaemonEventsChangeNameEvent* self);
static void daemon_events_change_name_event_finalize (GObject* obj);
static void _vala_daemon_events_change_name_event_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_daemon_events_change_name_event_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


DaemonEventsChangeNameEvent* daemon_events_change_name_event_construct (GType object_type, const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server) {
	DaemonEventsChangeNameEvent * self = NULL;
	g_return_val_if_fail (username != NULL, NULL);
	g_return_val_if_fail (newUsername != NULL, NULL);
	g_return_val_if_fail (channel != NULL, NULL);
	g_return_val_if_fail (server != NULL, NULL);
	self = (DaemonEventsChangeNameEvent*) daemon_events_log_event_construct (object_type, username, channel, server);
	daemon_events_change_name_event_set_NewUsername (self, newUsername);
	return self;
}


DaemonEventsChangeNameEvent* daemon_events_change_name_event_new (const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server) {
	return daemon_events_change_name_event_construct (DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, username, newUsername, channel, server);
}


DaemonEventsChangeNameEvent* daemon_events_change_name_event_construct_WithTimestamp (GType object_type, const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server, GDateTime* timestamp) {
	DaemonEventsChangeNameEvent * self = NULL;
	g_return_val_if_fail (username != NULL, NULL);
	g_return_val_if_fail (newUsername != NULL, NULL);
	g_return_val_if_fail (channel != NULL, NULL);
	g_return_val_if_fail (server != NULL, NULL);
	g_return_val_if_fail (timestamp != NULL, NULL);
	self = (DaemonEventsChangeNameEvent*) daemon_events_log_event_construct_WithTimestamp (object_type, username, channel, server, timestamp);
	daemon_events_change_name_event_set_NewUsername (self, newUsername);
	return self;
}


DaemonEventsChangeNameEvent* daemon_events_change_name_event_new_WithTimestamp (const gchar* username, const gchar* newUsername, const gchar* channel, const gchar* server, GDateTime* timestamp) {
	return daemon_events_change_name_event_construct_WithTimestamp (DAEMON_EVENTS_TYPE_CHANGE_NAME_EVENT, username, newUsername, channel, server, timestamp);
}


static gchar* daemon_events_change_name_event_real_ToString (DaemonEventsLogEvent* base) {
	DaemonEventsChangeNameEvent * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	self = (DaemonEventsChangeNameEvent*) base;
	_tmp0_ = daemon_events_log_event_get_TimestampString ((DaemonEventsLogEvent*) self);
	_tmp1_ = daemon_events_log_event_get_Username ((DaemonEventsLogEvent*) self);
	_tmp2_ = daemon_events_log_event_get_Channel ((DaemonEventsLogEvent*) self);
	_tmp3_ = daemon_events_log_event_get_Server ((DaemonEventsLogEvent*) self);
	_tmp4_ = g_strdup_printf (DAEMON_EVENTS_CHANGE_NAME_EVENT__stringFormat, _tmp0_, _tmp1_, _tmp2_, _tmp3_, self->priv->_NewUsername);
	result = _tmp4_;
	return result;
}


const gchar* daemon_events_change_name_event_get_NewUsername (DaemonEventsChangeNameEvent* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_NewUsername;
	return result;
}


static void daemon_events_change_name_event_set_NewUsername (DaemonEventsChangeNameEvent* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_NewUsername);
	self->priv->_NewUsername = _tmp0_;
	g_object_notify ((GObject *) self, "NewUsername");
}


static void daemon_events_change_name_event_class_init (DaemonEventsChangeNameEventClass * klass) {
	daemon_events_change_name_event_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DaemonEventsChangeNameEventPrivate));
	DAEMON_EVENTS_LOG_EVENT_CLASS (klass)->ToString = daemon_events_change_name_event_real_ToString;
	G_OBJECT_CLASS (klass)->get_property = _vala_daemon_events_change_name_event_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_daemon_events_change_name_event_set_property;
	G_OBJECT_CLASS (klass)->finalize = daemon_events_change_name_event_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), DAEMON_EVENTS_CHANGE_NAME_EVENT_NEW_USERNAME, g_param_spec_string ("NewUsername", "NewUsername", "NewUsername", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void daemon_events_change_name_event_instance_init (DaemonEventsChangeNameEvent * self) {
	self->priv = DAEMON_EVENTS_CHANGE_NAME_EVENT_GET_PRIVATE (self);
}


static void daemon_events_change_name_event_finalize (GObject* obj) {
	DaemonEventsChangeNameEvent * self;
	self = DAEMON_EVENTS_CHANGE_NAME_EVENT (obj);
	_g_free0 (self->priv->_NewUsername);
	G_OBJECT_CLASS (daemon_events_change_name_event_parent_class)->finalize (obj);
}


GType daemon_events_change_name_event_get_type (void) {
	static volatile gsize daemon_events_change_name_event_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_events_change_name_event_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DaemonEventsChangeNameEventClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) daemon_events_change_name_event_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DaemonEventsChangeNameEvent), 0, (GInstanceInitFunc) daemon_events_change_name_event_instance_init, NULL };
		GType daemon_events_change_name_event_type_id;
		daemon_events_change_name_event_type_id = g_type_register_static (DAEMON_EVENTS_TYPE_LOG_EVENT, "DaemonEventsChangeNameEvent", &g_define_type_info, 0);
		g_once_init_leave (&daemon_events_change_name_event_type_id__volatile, daemon_events_change_name_event_type_id);
	}
	return daemon_events_change_name_event_type_id__volatile;
}


static void _vala_daemon_events_change_name_event_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DaemonEventsChangeNameEvent * self;
	self = DAEMON_EVENTS_CHANGE_NAME_EVENT (object);
	switch (property_id) {
		case DAEMON_EVENTS_CHANGE_NAME_EVENT_NEW_USERNAME:
		g_value_set_string (value, daemon_events_change_name_event_get_NewUsername (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_daemon_events_change_name_event_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DaemonEventsChangeNameEvent * self;
	self = DAEMON_EVENTS_CHANGE_NAME_EVENT (object);
	switch (property_id) {
		case DAEMON_EVENTS_CHANGE_NAME_EVENT_NEW_USERNAME:
		daemon_events_change_name_event_set_NewUsername (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



