/* EmailSender.c generated by valac 0.12.0, the Vala compiler
 * generated from EmailSender.vala, do not modify */

/*SemesterLeistung - An IRC Daemon
* Copyright (C) 2011  Simon Baumer
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define DAEMON_TYPE_EMAIL_SENDER (daemon_email_sender_get_type ())
#define DAEMON_EMAIL_SENDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_TYPE_EMAIL_SENDER, DaemonEmailSender))
#define DAEMON_EMAIL_SENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_TYPE_EMAIL_SENDER, DaemonEmailSenderClass))
#define DAEMON_IS_EMAIL_SENDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_TYPE_EMAIL_SENDER))
#define DAEMON_IS_EMAIL_SENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_TYPE_EMAIL_SENDER))
#define DAEMON_EMAIL_SENDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_TYPE_EMAIL_SENDER, DaemonEmailSenderClass))

typedef struct _DaemonEmailSender DaemonEmailSender;
typedef struct _DaemonEmailSenderClass DaemonEmailSenderClass;
typedef struct _DaemonEmailSenderPrivate DaemonEmailSenderPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define DAEMON_TYPE_SMTP_CONFIGURATION (daemon_smtp_configuration_get_type ())
#define DAEMON_SMTP_CONFIGURATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_TYPE_SMTP_CONFIGURATION, DaemonSmtpConfiguration))
#define DAEMON_SMTP_CONFIGURATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_TYPE_SMTP_CONFIGURATION, DaemonSmtpConfigurationClass))
#define DAEMON_IS_SMTP_CONFIGURATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_TYPE_SMTP_CONFIGURATION))
#define DAEMON_IS_SMTP_CONFIGURATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_TYPE_SMTP_CONFIGURATION))
#define DAEMON_SMTP_CONFIGURATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_TYPE_SMTP_CONFIGURATION, DaemonSmtpConfigurationClass))

typedef struct _DaemonSmtpConfiguration DaemonSmtpConfiguration;
typedef struct _DaemonSmtpConfigurationClass DaemonSmtpConfigurationClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define DAEMON_TYPE_CONSOLE_COLORS (daemon_console_colors_get_type ())
typedef struct _DaemonParamSpecEmailSender DaemonParamSpecEmailSender;

typedef enum  {
	DAEMON_EMAIL_ERROR_ServerFailed,
	DAEMON_EMAIL_ERROR_DNSError
} DaemonEmailError;
#define DAEMON_EMAIL_ERROR daemon_email_error_quark ()
struct _DaemonEmailSender {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DaemonEmailSenderPrivate * priv;
};

struct _DaemonEmailSenderClass {
	GTypeClass parent_class;
	void (*finalize) (DaemonEmailSender *self);
};

struct _DaemonEmailSenderPrivate {
	GSocketClient* _connection;
	GSocketConnection* _socket;
	GDataInputStream* _inputStream;
};

typedef enum  {
	DAEMON_CONSOLE_COLORS_Red = 31,
	DAEMON_CONSOLE_COLORS_Green = 32,
	DAEMON_CONSOLE_COLORS_Yellow = 33,
	DAEMON_CONSOLE_COLORS_Blue = 34,
	DAEMON_CONSOLE_COLORS_Purple = 35,
	DAEMON_CONSOLE_COLORS_Cyan = 36,
	DAEMON_CONSOLE_COLORS_White = 37
} DaemonConsoleColors;

struct _DaemonParamSpecEmailSender {
	GParamSpec parent_instance;
};


static gpointer daemon_email_sender_parent_class = NULL;
static DaemonSmtpConfiguration* daemon_email_sender__Configuration;
static DaemonSmtpConfiguration* daemon_email_sender__Configuration = NULL;

GQuark daemon_email_error_quark (void);
gpointer daemon_email_sender_ref (gpointer instance);
void daemon_email_sender_unref (gpointer instance);
GParamSpec* daemon_param_spec_email_sender (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void daemon_value_set_email_sender (GValue* value, gpointer v_object);
void daemon_value_take_email_sender (GValue* value, gpointer v_object);
gpointer daemon_value_get_email_sender (const GValue* value);
GType daemon_email_sender_get_type (void) G_GNUC_CONST;
#define DAEMON_EMAIL_SENDER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DAEMON_TYPE_EMAIL_SENDER, DaemonEmailSenderPrivate))
enum  {
	DAEMON_EMAIL_SENDER_DUMMY_PROPERTY
};
GType daemon_smtp_configuration_get_type (void) G_GNUC_CONST;
void daemon_email_sender_SendEmail (DaemonEmailSender* self, const gchar* receiver, const gchar* subject, const gchar* body, GError** error);
DaemonSmtpConfiguration* daemon_email_sender_get_Configuration (void);
const gchar* daemon_smtp_configuration_get_Host (DaemonSmtpConfiguration* self);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
guint16 daemon_smtp_configuration_get_Port (DaemonSmtpConfiguration* self);
static void daemon_email_sender_Read (DaemonEmailSender* self, GError** error);
static void daemon_email_sender_Write (DaemonEmailSender* self, const gchar* text, GError** error);
const gchar* daemon_smtp_configuration_get_Sender (DaemonSmtpConfiguration* self);
GType daemon_console_colors_get_type (void) G_GNUC_CONST;
void daemon_global_log_ColorMessage (DaemonConsoleColors color, const gchar* format, ...);
DaemonEmailSender* daemon_email_sender_new (void);
DaemonEmailSender* daemon_email_sender_construct (GType object_type);
void daemon_email_sender_set_Configuration (DaemonSmtpConfiguration* value);
static void daemon_email_sender_finalize (DaemonEmailSender* obj);


GQuark daemon_email_error_quark (void) {
	return g_quark_from_static_string ("daemon_email_error-quark");
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


void daemon_email_sender_SendEmail (DaemonEmailSender* self, const gchar* receiver, const gchar* subject, const gchar* body, GError** error) {
	GResolver* _tmp0_ = NULL;
	GResolver* _tmp1_;
	GResolver* resolver;
	GList* addresses = NULL;
	DaemonSmtpConfiguration* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	GList* _tmp5_;
	guint _tmp7_;
	gconstpointer _tmp14_ = NULL;
	GInetAddress* _tmp15_;
	GInetAddress* address;
	DaemonSmtpConfiguration* _tmp16_ = NULL;
	guint16 _tmp17_;
	GInetSocketAddress* _tmp18_ = NULL;
	GInetSocketAddress* endpoint;
	GSocketClient* _tmp19_ = NULL;
	gchar* localAddress = NULL;
	GSocketConnection* _tmp20_ = NULL;
	GSocketConnection* _tmp21_;
	GSocketConnection* _tmp22_;
	GInputStream* _tmp23_ = NULL;
	GDataInputStream* _tmp24_ = NULL;
	GSocketAddress* _tmp25_ = NULL;
	GSocketAddress* _tmp26_;
	GInetAddress* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	DaemonSmtpConfiguration* _tmp33_ = NULL;
	const gchar* _tmp34_ = NULL;
	DaemonSmtpConfiguration* _tmp35_ = NULL;
	const gchar* _tmp36_ = NULL;
	gchar* _tmp37_;
	gchar* _tmp38_;
	gchar* _tmp39_;
	gchar* _tmp40_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (receiver != NULL);
	g_return_if_fail (subject != NULL);
	g_return_if_fail (body != NULL);
	_tmp0_ = g_resolver_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	resolver = _tmp1_;
	_tmp2_ = daemon_email_sender_get_Configuration ();
	_tmp3_ = daemon_smtp_configuration_get_Host (_tmp2_);
	_tmp4_ = g_resolver_lookup_by_name (resolver, _tmp3_, NULL, &_inner_error_);
	_tmp5_ = _tmp4_;
	if (_inner_error_ != NULL) {
		goto __catch6_g_error;
	}
	__g_list_free__g_object_unref0_0 (addresses);
	addresses = _tmp5_;
	goto __finally6;
	__catch6_g_error:
	{
		GError * _error_;
		GError* _tmp6_ = NULL;
		_error_ = _inner_error_;
		_inner_error_ = NULL;
		_tmp6_ = g_error_new_literal (DAEMON_EMAIL_ERROR, DAEMON_EMAIL_ERROR_DNSError, _error_->message);
		_inner_error_ = _tmp6_;
		_g_error_free0 (_error_);
		goto __finally6;
	}
	__finally6:
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == DAEMON_EMAIL_ERROR) {
			g_propagate_error (error, _inner_error_);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			return;
		} else {
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp7_ = g_list_length (addresses);
	if (_tmp7_ == 0) {
		DaemonSmtpConfiguration* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gchar* _tmp10_;
		gchar* _tmp11_;
		GError* _tmp12_ = NULL;
		GError* _tmp13_;
		_tmp8_ = daemon_email_sender_get_Configuration ();
		_tmp9_ = daemon_smtp_configuration_get_Host (_tmp8_);
		_tmp10_ = g_strconcat ("No IP found for ", _tmp9_, NULL);
		_tmp11_ = _tmp10_;
		_tmp12_ = g_error_new_literal (DAEMON_EMAIL_ERROR, DAEMON_EMAIL_ERROR_DNSError, _tmp11_);
		_tmp13_ = _tmp12_;
		_g_free0 (_tmp11_);
		_inner_error_ = _tmp13_;
		if (_inner_error_->domain == DAEMON_EMAIL_ERROR) {
			g_propagate_error (error, _inner_error_);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			return;
		} else {
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp14_ = g_list_nth_data (addresses, (guint) 0);
	_tmp15_ = _g_object_ref0 ((GInetAddress*) _tmp14_);
	address = _tmp15_;
	_tmp16_ = daemon_email_sender_get_Configuration ();
	_tmp17_ = daemon_smtp_configuration_get_Port (_tmp16_);
	_tmp18_ = (GInetSocketAddress*) g_inet_socket_address_new (address, _tmp17_);
	endpoint = _tmp18_;
	_tmp19_ = g_socket_client_new ();
	_g_object_unref0 (self->priv->_connection);
	self->priv->_connection = _tmp19_;
	_tmp20_ = g_socket_client_connect (self->priv->_connection, (GSocketConnectable*) endpoint, NULL, &_inner_error_);
	_tmp21_ = _tmp20_;
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	_tmp22_ = _g_object_ref0 (_tmp21_);
	_g_object_unref0 (self->priv->_socket);
	self->priv->_socket = _tmp22_;
	_tmp23_ = g_io_stream_get_input_stream ((GIOStream*) self->priv->_socket);
	_tmp24_ = g_data_input_stream_new (_tmp23_);
	_g_object_unref0 (self->priv->_inputStream);
	self->priv->_inputStream = _tmp24_;
	_tmp25_ = g_socket_connection_get_local_address (self->priv->_socket, &_inner_error_);
	_tmp26_ = _tmp25_;
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	_tmp27_ = g_inet_socket_address_get_address (G_INET_SOCKET_ADDRESS (_tmp26_));
	_tmp28_ = g_inet_address_to_string (_tmp27_);
	_g_free0 (localAddress);
	localAddress = _tmp28_;
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	_tmp29_ = g_strconcat ("HELO ", localAddress, NULL);
	_tmp30_ = _tmp29_;
	_tmp31_ = g_strconcat (_tmp30_, "\r\n", NULL);
	_tmp32_ = _tmp31_;
	daemon_email_sender_Write (self, _tmp32_, &_inner_error_);
	_g_free0 (_tmp32_);
	_g_free0 (_tmp30_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "MAIL FROM: ", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	_tmp33_ = daemon_email_sender_get_Configuration ();
	_tmp34_ = daemon_smtp_configuration_get_Sender (_tmp33_);
	daemon_email_sender_Write (self, _tmp34_, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "\r\n", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "VRFY ", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	_tmp35_ = daemon_email_sender_get_Configuration ();
	_tmp36_ = daemon_smtp_configuration_get_Sender (_tmp35_);
	daemon_email_sender_Write (self, _tmp36_, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "\r\n", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "RCPT TO: ", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, receiver, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "\r\n", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "DATA\r\n", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "Subject: ", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	_tmp37_ = g_strconcat (subject, "\r\n", NULL);
	_tmp38_ = _tmp37_;
	daemon_email_sender_Write (self, _tmp38_, &_inner_error_);
	_g_free0 (_tmp38_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	_tmp39_ = g_strconcat (body, "\r\n", NULL);
	_tmp40_ = _tmp39_;
	daemon_email_sender_Write (self, _tmp40_, &_inner_error_);
	_g_free0 (_tmp40_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, ".\r\n", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Write (self, "QUIT\r\n", &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	daemon_email_sender_Read (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		goto __catch7_g_error;
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError * _error_;
		GError* _tmp41_ = NULL;
		_error_ = _inner_error_;
		_inner_error_ = NULL;
		_tmp41_ = g_error_new_literal (DAEMON_EMAIL_ERROR, DAEMON_EMAIL_ERROR_ServerFailed, _error_->message);
		_inner_error_ = _tmp41_;
		_g_error_free0 (_error_);
		goto __finally7;
	}
	__finally7:
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == DAEMON_EMAIL_ERROR) {
			g_propagate_error (error, _inner_error_);
			_g_free0 (localAddress);
			_g_object_unref0 (endpoint);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			return;
		} else {
			_g_free0 (localAddress);
			_g_object_unref0 (endpoint);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	daemon_global_log_ColorMessage (DAEMON_CONSOLE_COLORS_Green, "Successfully sent E-Mail with subject '%s' to '%s', body:", subject, receiver);
	daemon_global_log_ColorMessage (DAEMON_CONSOLE_COLORS_Cyan, "%s", body);
	_g_free0 (localAddress);
	_g_object_unref0 (endpoint);
	_g_object_unref0 (address);
	__g_list_free__g_object_unref0_0 (addresses);
	_g_object_unref0 (resolver);
}


static void daemon_email_sender_Read (DaemonEmailSender* self, GError** error) {
	gsize size = 0UL;
	gsize _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = g_data_input_stream_read_line (self->priv->_inputStream, &_tmp0_, NULL, &_inner_error_);
	size = _tmp0_;
	_tmp2_ = _tmp1_;
	_g_free0 (_tmp2_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_IO_ERROR) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	guint8* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = -1;
	_tmp0_ = strlen (self);
	res_length1 = (gint) _tmp0_;
	_tmp1_ = res;
	*result_length1 = res_length1;
	result = _tmp1_;
	return result;
}


static void daemon_email_sender_Write (DaemonEmailSender* self, const gchar* text, GError** error) {
	GOutputStream* _tmp0_ = NULL;
	guint8* _tmp1_ = NULL;
	gint _tmp2_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (text != NULL);
	_tmp0_ = g_io_stream_get_output_stream ((GIOStream*) self->priv->_socket);
	_tmp1_ = string_get_data (text, &_tmp2_);
	g_output_stream_write (_tmp0_, _tmp1_, (gsize) _tmp2_, NULL, &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_IO_ERROR) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
}


DaemonEmailSender* daemon_email_sender_construct (GType object_type) {
	DaemonEmailSender* self = NULL;
	self = (DaemonEmailSender*) g_type_create_instance (object_type);
	return self;
}


DaemonEmailSender* daemon_email_sender_new (void) {
	return daemon_email_sender_construct (DAEMON_TYPE_EMAIL_SENDER);
}


DaemonSmtpConfiguration* daemon_email_sender_get_Configuration (void) {
	DaemonSmtpConfiguration* result;
	result = daemon_email_sender__Configuration;
	return result;
}


void daemon_email_sender_set_Configuration (DaemonSmtpConfiguration* value) {
	DaemonSmtpConfiguration* _tmp0_;
	_tmp0_ = _g_object_ref0 (value);
	_g_object_unref0 (daemon_email_sender__Configuration);
	daemon_email_sender__Configuration = _tmp0_;
}


static void daemon_value_email_sender_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void daemon_value_email_sender_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		daemon_email_sender_unref (value->data[0].v_pointer);
	}
}


static void daemon_value_email_sender_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = daemon_email_sender_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer daemon_value_email_sender_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* daemon_value_email_sender_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		DaemonEmailSender* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = daemon_email_sender_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* daemon_value_email_sender_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	DaemonEmailSender** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = daemon_email_sender_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* daemon_param_spec_email_sender (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	DaemonParamSpecEmailSender* spec;
	g_return_val_if_fail (g_type_is_a (object_type, DAEMON_TYPE_EMAIL_SENDER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer daemon_value_get_email_sender (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DAEMON_TYPE_EMAIL_SENDER), NULL);
	return value->data[0].v_pointer;
}


void daemon_value_set_email_sender (GValue* value, gpointer v_object) {
	DaemonEmailSender* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DAEMON_TYPE_EMAIL_SENDER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DAEMON_TYPE_EMAIL_SENDER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		daemon_email_sender_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		daemon_email_sender_unref (old);
	}
}


void daemon_value_take_email_sender (GValue* value, gpointer v_object) {
	DaemonEmailSender* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DAEMON_TYPE_EMAIL_SENDER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DAEMON_TYPE_EMAIL_SENDER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		daemon_email_sender_unref (old);
	}
}


static void daemon_email_sender_class_init (DaemonEmailSenderClass * klass) {
	daemon_email_sender_parent_class = g_type_class_peek_parent (klass);
	DAEMON_EMAIL_SENDER_CLASS (klass)->finalize = daemon_email_sender_finalize;
	g_type_class_add_private (klass, sizeof (DaemonEmailSenderPrivate));
}


static void daemon_email_sender_instance_init (DaemonEmailSender * self) {
	self->priv = DAEMON_EMAIL_SENDER_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void daemon_email_sender_finalize (DaemonEmailSender* obj) {
	DaemonEmailSender * self;
	self = DAEMON_EMAIL_SENDER (obj);
	_g_object_unref0 (self->priv->_connection);
	_g_object_unref0 (self->priv->_socket);
	_g_object_unref0 (self->priv->_inputStream);
}


GType daemon_email_sender_get_type (void) {
	static volatile gsize daemon_email_sender_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_email_sender_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { daemon_value_email_sender_init, daemon_value_email_sender_free_value, daemon_value_email_sender_copy_value, daemon_value_email_sender_peek_pointer, "p", daemon_value_email_sender_collect_value, "p", daemon_value_email_sender_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (DaemonEmailSenderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) daemon_email_sender_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DaemonEmailSender), 0, (GInstanceInitFunc) daemon_email_sender_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType daemon_email_sender_type_id;
		daemon_email_sender_type_id = g_type_register_fundamental (g_type_fundamental_next (), "DaemonEmailSender", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&daemon_email_sender_type_id__volatile, daemon_email_sender_type_id);
	}
	return daemon_email_sender_type_id__volatile;
}


gpointer daemon_email_sender_ref (gpointer instance) {
	DaemonEmailSender* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void daemon_email_sender_unref (gpointer instance) {
	DaemonEmailSender* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		DAEMON_EMAIL_SENDER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



