/* IDataAccess.c generated by valac 0.12.0, the Vala compiler
 * generated from IDataAccess.vala, do not modify */

/*SemesterLeistung - An IRC Daemon
* Copyright (C) 2011  Simon Baumer
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define DAEMON_DATA_TYPE_EVENT_TYPES (daemon_data_event_types_get_type ())

#define DAEMON_DATA_TYPE_IDATA_ACCESS (daemon_data_idata_access_get_type ())
#define DAEMON_DATA_IDATA_ACCESS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_DATA_TYPE_IDATA_ACCESS, DaemonDataIDataAccess))
#define DAEMON_DATA_IS_IDATA_ACCESS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_DATA_TYPE_IDATA_ACCESS))
#define DAEMON_DATA_IDATA_ACCESS_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), DAEMON_DATA_TYPE_IDATA_ACCESS, DaemonDataIDataAccessIface))

typedef struct _DaemonDataIDataAccess DaemonDataIDataAccess;
typedef struct _DaemonDataIDataAccessIface DaemonDataIDataAccessIface;

#define DAEMON_EVENTS_TYPE_LOG_EVENT (daemon_events_log_event_get_type ())
#define DAEMON_EVENTS_LOG_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEvent))
#define DAEMON_EVENTS_LOG_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEventClass))
#define DAEMON_EVENTS_IS_LOG_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT))
#define DAEMON_EVENTS_IS_LOG_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_EVENTS_TYPE_LOG_EVENT))
#define DAEMON_EVENTS_LOG_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_EVENTS_TYPE_LOG_EVENT, DaemonEventsLogEventClass))

typedef struct _DaemonEventsLogEvent DaemonEventsLogEvent;
typedef struct _DaemonEventsLogEventClass DaemonEventsLogEventClass;

#define DAEMON_DATA_TYPE_IRC_LOG (daemon_data_irc_log_get_type ())
#define DAEMON_DATA_IRC_LOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DAEMON_DATA_TYPE_IRC_LOG, DaemonDataIRCLog))
#define DAEMON_DATA_IRC_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DAEMON_DATA_TYPE_IRC_LOG, DaemonDataIRCLogClass))
#define DAEMON_DATA_IS_IRC_LOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DAEMON_DATA_TYPE_IRC_LOG))
#define DAEMON_DATA_IS_IRC_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DAEMON_DATA_TYPE_IRC_LOG))
#define DAEMON_DATA_IRC_LOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DAEMON_DATA_TYPE_IRC_LOG, DaemonDataIRCLogClass))

typedef struct _DaemonDataIRCLog DaemonDataIRCLog;
typedef struct _DaemonDataIRCLogClass DaemonDataIRCLogClass;
typedef struct _DaemonDataIRCLogPrivate DaemonDataIRCLogPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

typedef enum  {
	DAEMON_DATA_DATA_ACCESS_ERROR_OpenFailed,
	DAEMON_DATA_DATA_ACCESS_ERROR_WriteError,
	DAEMON_DATA_DATA_ACCESS_ERROR_ReadError
} DaemonDataDataAccessError;
#define DAEMON_DATA_DATA_ACCESS_ERROR daemon_data_data_access_error_quark ()
typedef enum  {
	DAEMON_DATA_EVENT_TYPES_Joined = 0,
	DAEMON_DATA_EVENT_TYPES_Left = 1,
	DAEMON_DATA_EVENT_TYPES_ChangedName = 2,
	DAEMON_DATA_EVENT_TYPES_Message = 3
} DaemonDataEventTypes;

struct _DaemonDataIDataAccessIface {
	GTypeInterface parent_iface;
	void (*Log) (DaemonDataIDataAccess* self, DaemonEventsLogEvent* event, GError** error);
	GDateTime* (*UserLastSeen) (DaemonDataIDataAccess* self, const gchar* username, const gchar* channel, const gchar* server, GError** error);
	GList* (*GetLog) (DaemonDataIDataAccess* self, const gchar* channel, const gchar* server, GError** error);
	void (*Init) (DaemonDataIDataAccess* self, const gchar* logPath, GError** error);
};

struct _DaemonDataIRCLog {
	GObject parent_instance;
	DaemonDataIRCLogPrivate * priv;
};

struct _DaemonDataIRCLogClass {
	GObjectClass parent_class;
};


static gpointer daemon_data_irc_log_parent_class = NULL;

GQuark daemon_data_data_access_error_quark (void);
GType daemon_data_event_types_get_type (void) G_GNUC_CONST;
GType daemon_events_log_event_get_type (void) G_GNUC_CONST;
GType daemon_data_idata_access_get_type (void) G_GNUC_CONST;
void daemon_data_idata_access_Log (DaemonDataIDataAccess* self, DaemonEventsLogEvent* event, GError** error);
GDateTime* daemon_data_idata_access_UserLastSeen (DaemonDataIDataAccess* self, const gchar* username, const gchar* channel, const gchar* server, GError** error);
GList* daemon_data_idata_access_GetLog (DaemonDataIDataAccess* self, const gchar* channel, const gchar* server, GError** error);
void daemon_data_idata_access_Init (DaemonDataIDataAccess* self, const gchar* logPath, GError** error);
GType daemon_data_irc_log_get_type (void) G_GNUC_CONST;
enum  {
	DAEMON_DATA_IRC_LOG_DUMMY_PROPERTY
};
void daemon_data_irc_log_Log (DaemonEventsLogEvent* event, GError** error);
void daemon_global_log_Message (const gchar* format, ...);
gchar* daemon_events_log_event_ToString (DaemonEventsLogEvent* self);
DaemonDataIDataAccess* daemon_plugin_manager_get_DataAccess (void);
DaemonDataIRCLog* daemon_data_irc_log_new (void);
DaemonDataIRCLog* daemon_data_irc_log_construct (GType object_type);


GQuark daemon_data_data_access_error_quark (void) {
	return g_quark_from_static_string ("daemon_data_data_access_error-quark");
}


GType daemon_data_event_types_get_type (void) {
	static volatile gsize daemon_data_event_types_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_data_event_types_type_id__volatile)) {
		static const GEnumValue values[] = {{DAEMON_DATA_EVENT_TYPES_Joined, "DAEMON_DATA_EVENT_TYPES_Joined", "joined"}, {DAEMON_DATA_EVENT_TYPES_Left, "DAEMON_DATA_EVENT_TYPES_Left", "left"}, {DAEMON_DATA_EVENT_TYPES_ChangedName, "DAEMON_DATA_EVENT_TYPES_ChangedName", "changedname"}, {DAEMON_DATA_EVENT_TYPES_Message, "DAEMON_DATA_EVENT_TYPES_Message", "message"}, {0, NULL, NULL}};
		GType daemon_data_event_types_type_id;
		daemon_data_event_types_type_id = g_enum_register_static ("DaemonDataEventTypes", values);
		g_once_init_leave (&daemon_data_event_types_type_id__volatile, daemon_data_event_types_type_id);
	}
	return daemon_data_event_types_type_id__volatile;
}


void daemon_data_idata_access_Log (DaemonDataIDataAccess* self, DaemonEventsLogEvent* event, GError** error) {
	DAEMON_DATA_IDATA_ACCESS_GET_INTERFACE (self)->Log (self, event, error);
}


GDateTime* daemon_data_idata_access_UserLastSeen (DaemonDataIDataAccess* self, const gchar* username, const gchar* channel, const gchar* server, GError** error) {
	return DAEMON_DATA_IDATA_ACCESS_GET_INTERFACE (self)->UserLastSeen (self, username, channel, server, error);
}


GList* daemon_data_idata_access_GetLog (DaemonDataIDataAccess* self, const gchar* channel, const gchar* server, GError** error) {
	return DAEMON_DATA_IDATA_ACCESS_GET_INTERFACE (self)->GetLog (self, channel, server, error);
}


void daemon_data_idata_access_Init (DaemonDataIDataAccess* self, const gchar* logPath, GError** error) {
	DAEMON_DATA_IDATA_ACCESS_GET_INTERFACE (self)->Init (self, logPath, error);
}


static void daemon_data_idata_access_base_init (DaemonDataIDataAccessIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType daemon_data_idata_access_get_type (void) {
	static volatile gsize daemon_data_idata_access_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_data_idata_access_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DaemonDataIDataAccessIface), (GBaseInitFunc) daemon_data_idata_access_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType daemon_data_idata_access_type_id;
		daemon_data_idata_access_type_id = g_type_register_static (G_TYPE_INTERFACE, "DaemonDataIDataAccess", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (daemon_data_idata_access_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&daemon_data_idata_access_type_id__volatile, daemon_data_idata_access_type_id);
	}
	return daemon_data_idata_access_type_id__volatile;
}


void daemon_data_irc_log_Log (DaemonEventsLogEvent* event, GError** error) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	DaemonDataIDataAccess* _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (event != NULL);
	_tmp0_ = daemon_events_log_event_ToString (event);
	_tmp1_ = _tmp0_;
	daemon_global_log_Message ("%s", _tmp1_);
	_g_free0 (_tmp1_);
	_tmp2_ = daemon_plugin_manager_get_DataAccess ();
	daemon_data_idata_access_Log (_tmp2_, event, &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == DAEMON_DATA_DATA_ACCESS_ERROR) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
}


DaemonDataIRCLog* daemon_data_irc_log_construct (GType object_type) {
	DaemonDataIRCLog * self = NULL;
	self = (DaemonDataIRCLog*) g_object_new (object_type, NULL);
	return self;
}


DaemonDataIRCLog* daemon_data_irc_log_new (void) {
	return daemon_data_irc_log_construct (DAEMON_DATA_TYPE_IRC_LOG);
}


static void daemon_data_irc_log_class_init (DaemonDataIRCLogClass * klass) {
	daemon_data_irc_log_parent_class = g_type_class_peek_parent (klass);
}


static void daemon_data_irc_log_instance_init (DaemonDataIRCLog * self) {
}


GType daemon_data_irc_log_get_type (void) {
	static volatile gsize daemon_data_irc_log_type_id__volatile = 0;
	if (g_once_init_enter (&daemon_data_irc_log_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DaemonDataIRCLogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) daemon_data_irc_log_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DaemonDataIRCLog), 0, (GInstanceInitFunc) daemon_data_irc_log_instance_init, NULL };
		GType daemon_data_irc_log_type_id;
		daemon_data_irc_log_type_id = g_type_register_static (G_TYPE_OBJECT, "DaemonDataIRCLog", &g_define_type_info, 0);
		g_once_init_leave (&daemon_data_irc_log_type_id__volatile, daemon_data_irc_log_type_id);
	}
	return daemon_data_irc_log_type_id__volatile;
}



